### PR TITLE
Fixes #580

### PR DESCRIPTION
**Pull request by imAneeesh**
## Explanation

  
Fixes #580:

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — APPROVED** [review]
Before we could merge this, kindly mention the issue number with the "Fixes" keyword. Also, check all the checkboxes.

**Comment by imAneeesh** [comment]
Yes,  changeed to fixes

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly mention the `issue number` associated with this pull request.

**Comment by imAneeesh** [comment]
Mentioned bro

**Comment by GowthamGoush** [comment]
> Mentioned bro

Actually, what you have mentioned is this pull request number.

**Comment by PradeepBaipadithaya** [comment]
Aneesh modalu issue create madida number update madbeku "Fixes#"

**Comment by amanjha8100** [comment]
@imAneeesh what is the update in this one, please do look into the changes requested?

**Pull request closed without merging**
