### PR TITLE
21 Number Game

### LINKED ISSUE #876: 21 Number Game
21, Bagram, or Twenty plus one is a game which progresses by counting up 1 to 21, with the player who calls “21” is eliminated. It can be played between any number of players.There will be some rules also.

@GowthamGoush assign me this.

### PR DESCRIPTION
**Pull request by rahulsrivastava1**
## Explanation
21 Number Game written in python language
Fixes #876 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by rahulsrivastava1** [comment]
Hey @RaveenaBhasin and @GowthamGoush kindly check it!

**Review by GowthamGoush — APPROVED** [review]
Hey, nice job!
Before merging, consider reformatting the readme as per #145.

**Comment by rahulsrivastava1** [comment]
Hey @GowthamGoush , i already create readme file where i detailed everything as per #145 . Please let me know what part is you looking for.

**Comment by GowthamGoush** [comment]
> Hey @GowthamGoush , i already create readme file where i detailed everything as per #145 . Please let me know what part is you looking for.

Could you please categorise the images based on input and output?

**Comment by rahulsrivastava1** [comment]
> > Hey @GowthamGoush , i already create readme file where i detailed everything as per #145 . Please let me know what part is you looking for.
> 
> Could you please categorise the images based on input and output?

This is a game so we will give input and output continuously not separate way... but i changed some lines kindly check it!

**Review by GowthamGoush — APPROVED** [review]
Alright then, no worries.

**Pull request merged**
