### PR TITLE
Tictactoe game 

### PR DESCRIPTION
**Pull request by nitya123-github**
developed a simple tictactoe game using a random number

### CODE REVIEW

**Comment by Tejas1510** [comment]
@nitya123-github are you a part of SWOC

**Comment by nitya123-github** [comment]
yea iam part of SWOC!

**Comment by Tejas1510** [comment]
@nitya123-github  it will be better if you create a simple UI using Tkinter

**Comment by Tejas1510** [comment]
The code looks Good but it will be better if you create a UI you will be awarded more Marks

**Comment by nitya123-github** [comment]
yeah okay! i will try to work on it

**Comment by nitya123-github** [comment]
created a todo app with user interface

**Comment by Tejas1510** [comment]
Awesome Work @nitya123-github

**Comment by nitya123-github** [comment]
thanks! But  where can I  see  the points for swoc

**Comment by nitya123-github** [comment]
thanks! But  where can I  see  the points for swoc?

**Comment by Tejas1510** [comment]
I don't have an idea about that
Organizer will decide that

**Comment by nitya123-github** [comment]
okay but will they know my contributions?

**Comment by Tejas1510** [comment]
See every issue have a SWOC label associated with it
And their code on backend checks that and award you respective points
This is what I Know since it is just a start, they will guide us respectively

**Comment by nitya123-github** [comment]
okay thanks for reply !

**Pull request merged**
