### PR TITLE
Adventure game using python

### LINKED ISSUE #607: Text Based Adventure game using Python

### PR DESCRIPTION
**Pull request by dhruv-varshney**
Fixes #607 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator has carefully read & adhere to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
There are various redundant files. Consider creating a new branch for a new issue.

Also, @dhruv-varshney, it seems like you have copied the code from the resources available online.

The motive of this open-source program is to provide the opportunity to learn how to contribute to open-source and learn something new. 
Copy/Pasting the code is not constructive, so kindly avoid such plagiarism, and I'm closing this pr.

**Comment by dhruv-varshney** [comment]
Hello @GowthamGoush  ya that story is a similar one which is there on website. If you are saying plag is there so I will change the story, then will it be plag free ,then??

**Comment by dhruv-varshney** [comment]
I really want to do this project..

**Comment by dhruv-varshney** [comment]
And sorry by mistake I pushed other useless files also. I will take care next time

**Pull request closed without merging**
