### PR TITLE
Added Dictionary in Python

### LINKED ISSUE #376: Dictionary (in Python)
Want to add a Dictionary created under tkinter GUI in python.
In this for data, I will be using a json file which will be imported in python code.
In this code I will also be implementing the case 
 i.) giving multiple meaning is there are many meanings
 ii.) giving meaning of closest word, if entered something wrong.

The dicitonary gui windows will look like this,

### PR DESCRIPTION
**Pull request by akash435**
Fixes #376

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### Description:
Added tkinter GUI based dictionary in python

### Change logs:
Used data from json file.

Below shows the screenshot of ho dictionary GUI window look like,

### CODE REVIEW

**Comment by akash435** [comment]
@thegautamkumarjaiswal , do you have any idea what will be the error, because many recent pr are getting the same error

**Comment by RaveenaBhasin** [comment]
@akash435 Update your Readme file acc. to #145

**Comment by thegautamkumarjaiswal** [comment]
> @thegautamkumarjaiswal , do you have any idea what will be the error, because many recent pr are getting the same error

No, now you update README file and @RaveenaBhasin will check and merge if all good.

**Comment by akash435** [comment]
@RaveenaBhasin , I updated the readme, please check it

**Comment by thegautamkumarjaiswal** [comment]
> @RaveenaBhasin , I updated the readme, please check it

@akash435 You also need to add all dependencies(requirements) you used in the program and How will other run your project in their system.

**Comment by RaveenaBhasin** [comment]
@akash435 Do make all the required changes and create the PR again.

**Pull request closed without merging**
