### PR TITLE
Magic 8ball in Python

### LINKED ISSUE #692: Magic-8_ball Python Project
**Is your feature request related to a problem? Please describe.**
Adding a Magic 8 ball project in python which takes in a yes/ no question and gives the answer.

**Additional context**
This project also uses the playsound library which can import sounds while the project runs

Please Assign me this issue under **LGMSOC21**

### PR DESCRIPTION
**Pull request by varshitha1707**
# Fixes: #692 

## Explanation

This is a basic python project which replicates the functionalities on an 8 Ball.
 You enter a question and the program gives you the answer.
  
Fixes #692  
and Read me with format #145 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

# looks something like this:

 Demo

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please consider removing the changes from this project repo's readme and adding the "Third-Party Libraries Required" subheading.

**Comment by varshitha1707** [comment]
> Please consider removing the changes from this project repo's readme and adding the "Third-Party Libraries Required" subheading.

Made the changes, Please Check. ThankYou

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
The readme of this script is good, but the changes in the main readme haven't been removed yet.
Please have a check on that.

**Review by GowthamGoush — COMMENTED** [review]
Alright, I still find the changes in the main readme file.

**Comment by varshitha1707** [comment]
@GowthamGoush I havent made any changes in the main readme.. it is even with the master branch. I made sure of it. 
I'm sorry for all the trouble.. but can you please check again?

**Review by GowthamGoush — COMMENTED** [review]
The changes in the readme exist yet. So what you can do is that copy/paste and commit the exact readme as in the repo, and there should be any changes found. Else try resetting the head in git and commit only the necessary files.

**Review by GowthamGoush — APPROVED** [review]
Good job!
Ready to be merged.

**Pull request merged**
