### PR TITLE
#953 Sign up and Registration Form

### LINKED ISSUE #953: Sign up And registration form
**Is your feature request related to a problem? Please describe.**
A sign up and registration form using React js 

**Describe the solution you'd like**
I will use React Js as front-end part and express js as backend and Mongodb as database

### PR DESCRIPTION
**Pull request by rajbir21-droid**
## Explanation
This is a complete authentication form made using React.js as front-end ,express.js as backend 
and MongoDB as database as every website require a sign-in and registration form to register their users
this script can be helpful to the one using React for the website. 
  
Fixes #953

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Would you please look at the files you are looking to add to your script in this PR?

**Comment by rajbir21-droid** [comment]
@GowthamGoush I have to edit something?

**Comment by GowthamGoush** [comment]
You've made more changes on more than 5k files. Most of these files are unnecessary for this script.

**Comment by rajbir21-droid** [comment]
okay removing them

**Comment by rajbir21-droid** [comment]
@GowthamGoush I have made the changes

**Review by GowthamGoush — COMMENTED** [review]
If those JSON files are unnecessary, you may remove them as well. Also, update the readme according to #145.

**Comment by rajbir21-droid** [comment]
I have updated the readme please have a look

**Comment by rajbir21-droid** [comment]
@GowthamGoush anything more I have change to this PR?

**Comment by GowthamGoush** [comment]
I'm not sure whether those JSON files are necessary. If not, please consider removing them.

**Comment by rajbir21-droid** [comment]
@GowthamGoush the JSON files maintain the dependencies that I have used in this project it will be needed when someone runs the command npm install

**Comment by GowthamGoush** [comment]
Alright, but from where did that node modules come from, which you removed earlier.

**Comment by rajbir21-droid** [comment]
Actually, those are the files of the dependencies that I have used  in this script , but these files can again be installed when someone runs the command npm install in the directory . At first ,I didn't know about this and pushed all the node modules but after you told me I read about this node modules and got to know, thanks for that.

**Comment by GowthamGoush** [comment]
Alright then.

**Review by GowthamGoush — APPROVED** [review]

**Pull request merged**
