### PR TITLE
issue #35

### LINKED ISSUE #35: Number Guessing Game in JAVA
The User guesses the number and CPU also guesses the number , whosoever has the less number of steps win.
I would like to work on this issue under SWoC 2021

### PR DESCRIPTION
**Pull request by N00Bmaster2810**
Fixes #35

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:
This is the Number guessing game implemented in JavaScript.

### Snapshot:
Added in the directory

### CODE REVIEW

**Comment by Tejas1510** [comment]
@N00Bmaster2810 add a readme file correctly explaning the sript with screenshot of input and output

**Comment by N00Bmaster2810** [comment]
@Tejas1510 sir I had added the readme

**Comment by tripathyprateek** [comment]
@N00Bmaster2810 can you move the css file to another file. Inline css is not really a good way to work. Works fine for me, but I would like if you could move the css to a css file.

**Review by tripathyprateek — CHANGES_REQUESTED** [review]
css in its own file to enhance code readability

**Comment by N00Bmaster2810** [comment]
> css in its own file to enhance code readability

Changes as requested are done, please review it.

**Pull request merged**
