### PR TITLE
Add Basic Calculator

### LINKED ISSUE #445: want to add Basic Calculator in python

### PR DESCRIPTION
**Pull request by rishabhrathore055**
## Explanation

  
Fixes #445 

## Checklist

- [x] The PR title starts with "Fix #issue_number. " 
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by rishabhrathore055** [comment]
@GowthamGoush pls check it Once

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by GowthamGoush** [comment]
One last thing, mention the issue number properly before getting this merged.

**Comment by rishabhrathore055** [comment]
@GowthamGoush Done ThankYou!!

**Pull request merged**
