### PR TITLE
added welcome bot

### PR DESCRIPTION
**Pull request by Sloth-Panda**
corresponds to issue -> #123

### CODE REVIEW

**Comment by tripathyprateek** [comment]
Thanks for this. Merging 🚀

**Comment by Sloth-Panda** [comment]
@tripathyprateek  can you please add swoc or dwoc which ever you are in tag and a level tag to it else it may not be counted so

**Comment by Sloth-Panda** [comment]
@Tejas1510  bro can you please add tags to the pr

**Comment by Tejas1510** [comment]
We don't need to have a tag for PR as it is assigned for the issue
Just keep on updating this file
https://docs.google.com/spreadsheets/d/1PQOim_z-zp9H_40HteKToHcr3gCWKQjjt-eZ3uatf0c/edit#gid=0

**Pull request merged**
