### PR TITLE
Added Keyboard pressed key detector in C Script

### LINKED ISSUE #442: Pressed Key Detector
Want to add this code under C language.

In this code, the program detects which key on the keyboard is pressed, either function key is pressed or normal key is presses.
In additon to this scan code everytime when a  key pressed.

language : C

### PR DESCRIPTION
**Pull request by akash435**
Fixes #442

## Explaination
In this C program described how keyboard detect which key  is pressed, either function key or any other key.

## Checklist

- [x] My branch is up-to-date with the main branch.
- [x] The PR is raised after the issue has been assigned to the PR creator.
- [x]  The PR creator have carefully read & adher to the guidelines of the project.
- [x]   The PR does not contain any unnecessary auto-generated code.
- [x]   The PR does not break any part of the existing code.

### CODE REVIEW

**Comment by akash435** [comment]
@Tejas1510 , @RaveenaBhasin, @GowthamGoush , created the pr  for adding C script for keyboard pressed key detector, please check it.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly follow the format for readme specified in #145.

**Comment by GowthamGoush** [comment]
Also, please don't remove the explanation and checklist section mentioned in the template while raising a pull request. Consider adding it again.

**Comment by akash435** [comment]
@GowthamGoush , I updated the readme as per format, and added checklist and explaination part in pr comment, please check it

**Review by GowthamGoush — APPROVED** [review]
Great job, @akash435!

**Comment by GowthamGoush** [comment]
Just make sure to fill in the explanation and checkboxes next time.

**Pull request merged**
