### PR TITLE
Added JS Live word counter

### LINKED ISSUE #702: JavaScript Words and Characters Live Counter
**Is your feature request related to a problem? Please describe.**
I would like to add a JS project which gives a live view of count when the user is typing words in the text field.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by supzi-del**
## Explanation

  
Fixes #702 

https://user-images.githubusercontent.com/78655439/123052816-ddca5980-d420-11eb-8a8b-9e9053513895.mp4

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please add a readme as per #145.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Could you please elaborate and follow the hierarchy of heading in the readme?

**Comment by supzi-del** [comment]
Is it okay now?

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
