### PR TITLE
Added Programming keyboard in python script

### LINKED ISSUE #822: Programming Keyboard
language : Python

In this script will try to create a virtual keyboard in which we will embed keys like 
print
int
char
string

and many other keys are are keywords in Programming language.

It will work like this, when we click on print key, it will write "print", when we click on int key, it will print "int",
So using this Programming Keyboard we don't need to write much, most works will be done by keyboard

### PR DESCRIPTION
**Pull request by akash435**
- A Programming Keyboard is an application created in python with tkinter gui.
- In this application user can enter any text or sentence or paragraph or any coding keyword of python using the virtual keyboard that is embedded inside keyboard button.
- This virtual keyboard can print any character (lower or uppercase), any special characters, digits, or any code snippet in python.
- Also there are clear, backspace, space, tab, hide keys also in this virtual keyboard.
- Also implemented the copy and paste also in the textarea.

Fixes #822

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

Below are some screenshots showing how it work:

### CODE REVIEW

**Comment by akash435** [comment]
@GowthamGoush @RaveenaBhasin , created a pr for adding Programming Keyword in python scripts, please check it.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by akash435** [comment]
@GowthamGoush , can i ask something, like which points will be counted, the label that we got while assigning or while merging?

**Comment by GowthamGoush** [comment]
> @GowthamGoush , can i ask something, like which points will be counted, the label that we got while assigning or while merging?

The label in the PR counts.

**Pull request merged**
