### PR TITLE
fix #640 Chrome Dino game

### LINKED ISSUE #640: Google chrome Dinosaur game in js
**Is your feature request related to a problem? Please describe.**
I want to add a dinosaur game that chrome has when there is network issue. I want to write this code in javascript

**Describe the solution you'd like**
I didn't find any code in js folder that has this game, since this is a classic client side game. I want this to be present in the js folder.

### PR DESCRIPTION
**Pull request by Saup21**
## The classic chrome dino game added in the js folder

  
Fixes #640 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Before merging, could you please consider shifting the "Tech stack" subheading above the images?

**Comment by Saup21** [comment]
Sure @GowthamGoush, can u increase the level to 4??
There were several minor bugs here and there that I had to fix

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by Saup21** [comment]
@GowthamGoush are you gonna make it level 4?

**Comment by GowthamGoush** [comment]
> Sure @GowthamGoush, can u increase the level to 4??
> There were several minor bugs here and there that I had to fix

I understand, but since we have been awarding level 4 labels to only those who have worked days together to get the complex script done, it won't pay justice to them if I award it to this script. Just because we have to be fair for all, please consider this.

**Comment by Saup21** [comment]
okay fine :D

**Pull request merged**
