### PR TITLE
Added TIC TAC TOE game in python

### LINKED ISSUE #351: TIC TAC TOE Game (in python)
Want to add TIC TAC TOE game in python.

The game will be single player mode.

The player has to play with computer , and computer also makes optimal moves by analyzing the moves of player.

The game will be totally played on console by running the source code.

### PR DESCRIPTION
**Pull request by akash435**
Added TIC TAC TOE game in python.

Fixes #351

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### Description:
This PR is about adding a TIC TAC TOE game to the python folder of this project.

### Change logs:
The game is single player mode.
The game is very optimally played by the computer, according to the algorithm defined in the code.

This is how the first look of game look like on running,

### CODE REVIEW

**Review by thegautamkumarjaiswal — CHANGES_REQUESTED** [review]
you can also use comments to define lines of code.

**Comment by akash435** [comment]
@thegautamkumarjaiswal , i did not got this, can can you please tell what i have to do now?

**Comment by thegautamkumarjaiswal** [comment]
> @thegautamkumarjaiswal , i did not got this, can can you please tell what i have to do now?

You can use python comment start with # to describe bit about packages, function you used. It will, help to understand more better.

**Comment by akash435** [comment]
Ok Sir

**Pull request closed without merging**
