### PR TITLE
added coffee-machine in python scripts

### PR DESCRIPTION
**Pull request by 5hre9a**
Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by Tejas1510** [comment]
@5hre9a I don't think so this issue was created
Can you tell me this pull request solve which issue

**Comment by 5hre9a** [comment]
Oops ....I just contributed randomly. Is it a must to contribute to those projects which are mentioned in the issues?

**Comment by Tejas1510** [comment]
@5hre9a you can first create a issue and I will then assign it to you and then you can create a PR for the same
Till then I am closing this PR

**Comment by 5hre9a** [comment]
#213

**Pull request closed without merging**
