### PR TITLE
FIX #587 AIRLINE BOOKING SYSTEM

### LINKED ISSUE #587: Airline Reservation System in C++
### Describe the solution you'd like: ###
This program can be described as a reservation system. It's capable of booking and canceling seats for specific days. For example, a seat on the 15th of May can be booked(the same seat cannot be booked on that specific day), and consequently canceled. It stores data in two 2-D integer arrays. It takes advantage of the fact that all data in an empty array is 0. It iterates over the dates until it finds a date with 0, at which it saves the user given date and seat number into the registry, or it finds a matching date, where it checks if the user given seat matches that registry. The same process is used for cancellation.

### PR DESCRIPTION
**Pull request by DhirajChauhan40**
## Explanation
  This is an Airline Booking System implemented in c++. This program can be described as a reservation system. It's capable of booking and canceling seats for specific days with user information. 

  
Fixes #587

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by DhirajChauhan40** [comment]
Can you reconsider on the level?
previously I didn't talk about user information in my issue, But here I have added that 
Thank YOu

**Review by GowthamGoush — COMMENTED** [review]
Before we could merge this pull request, please mention the issue number properly.

**Comment by DhirajChauhan40** [comment]
> Before we could merge this pull request, please mention the issue number properly.

@GowthamGoush FIXES#:587 to FIXES#587?

**Comment by GowthamGoush** [comment]
> > Before we could merge this pull request, please mention the issue number properly.
> 
> @GowthamGoush Fixes#:587 to Fixes#587?

Second one

**Comment by DhirajChauhan40** [comment]
> > > Before we could merge this pull request, please mention the issue number properly.
> > 
> > @GowthamGoush Fixes#:587 to Fixes#587?
> 
> Second one

done you can review now

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
