### PR TITLE
Add Bank Management System

### LINKED ISSUE #491: ADD: Bank(employee/staff)_Management_System
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by thegautamkumarjaiswal**
## Explanation

  
Fixes #491 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by thegautamkumarjaiswal** [comment]
@GowthamGoush please review the PR.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@thegautamkumarjaiswal, kindly consider removing the inappropriate changes that you have made.

**Comment by thegautamkumarjaiswal** [comment]
> @thegautamkumarjaiswal, kindly consider removing the inappropriate changes that you have made.

Ok sir I will consider.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@thegautamkumarjaiswal, it seems like you have copied the code from the resources available online. The motive of this open-source program is to provide the opportunity to learn how to contribute to open-source and learn something new. Copy/Pasting the code is not constructive, so kindly avoid such plagiarism, and I'm closing this issue.

**Comment by thegautamkumarjaiswal** [comment]
No, I haven't copied one line of code in my porgram, I know the importance of Open source that's why I am only contributing in Python language because I know it. Can you please reopen this PR. @GowthamGoush @Tejas1510

**Comment by GowthamGoush** [comment]
I'm sorry about that, @thegautamkumarjaiswal. The plagiarism level was quite high since most of your code was available in online resources. Kindly consider raising a new issue with a new script or raise a new PR for this issue.

**Comment by thegautamkumarjaiswal** [comment]
No problem, I know about it @Tejas1510 also talked about it on slack. This script I have made when I was learning python. I will create another PR for this issue.

**Comment by Tejas1510** [comment]
@thegautamkumarjaiswal it has come to our notice that you have copied the code from https://github.com/ganeshkavhar/Bank-management-system-in-Python

We encourage all the participants to refer to various blogs, Github repo, youtube videos but don't directly copy the code

if you add some features to the preexisting app then we can surely open the pr and think of merging it

Also, @GowthamGoush is having great experience in open source so he just helping you to get better and become a good developer 

So let's make the changes and get going good

**Comment by thegautamkumarjaiswal** [comment]
> @thegautamkumarjaiswal it has come to our notice that you have copied the code from https://github.com/ganeshkavhar/Bank-management-system-in-Python
> 
> We encourage all the participants to refer to various blogs, Github repo, youtube videos but don't directly copy the code
> 
> if you add some features to the preexisting app then we can surely open the pr and think of merging it
> 
> Also, @GowthamGoush is having great experience in open source so he just helping you to get better and become a good developer
> 
> So let's make the changes and get going good

sv

@Tejas1510 @GowthamGoush You can see here this is my all projects I have when from my starting journey in python. and some of course learning projects. Idk about it. I have cleared my word. and no problem if you thinking, I have to learn more then great i will learn. but I am not copying.

**Pull request closed without merging**
