### PR TITLE
Added the food recipe website

### LINKED ISSUE #938: Food-Recipe Application
Language : JavaScript

This web application will provide recipes for a plethora of dishes.
It will contain a search bar where we can search the dish and after the search is submitted, it will generate results for the specific dish.

### PR DESCRIPTION
**Pull request by Srijan1878**
## Explanation

  This is a food recipe application made with vanilla javascript which lets the users search several recipes for a dish
Fixes #938 

## Checklist

- [ ] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@Srijan1878, kindly add a readme as per #145.

**Comment by Srijan1878** [comment]
Okay!

**Comment by Srijan1878** [comment]
Added the readme file @GowthamGoush

**Review by GowthamGoush — COMMENTED** [review]
I believe you may remove those unnecessary comments.

**Comment by Srijan1878** [comment]
Done @GowthamGoush

**Pull request merged**
