### PR TITLE
QR Code Content Reader #510

### PR DESCRIPTION
**Pull request by tejasvi541**
### I have written the code for detecting the contents present in QR code using Python and OpenCv
Fixes #: #510

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@tejasvi541, it seems like you have copied the code from the resources available online. The motive of this open-source program is to provide the opportunity to learn how to contribute to open-source and learn something new. Copy/Pasting the code is not constructive, so kindly avoid such plagiarism, and I'm closing this issue.

**Comment by tejasvi541** [comment]
Hey @GowthamGoush , 
You might have some misunderstanding, this code is not written today but some days ago, this may be one of the ways doing this thing, but it is not copy-pasted as you have mentioned here, it would be great if you may provide me with the exact source or else please remove the plagiarism badge because if I had to indulge in such things I would not have given efforts in code and readme file itself. I don't know how to provide proof of me not doing plagiarism, so please look into this issue.
Thanks

**Comment by GowthamGoush** [comment]
@tejasvi541, after carefully going through your code, I found that 90% of it was reproduced from sources available online. I'll consider removing the label, but I can't consider this pull request. 
Also, please don't feel bad; it's totally fine. Go ahead and create a new issue and work faithfully.

**Comment by tejasvi541** [comment]
@GowthamGoush , Thanks really appreciate your consideration.

**Pull request closed without merging**
