### PR TITLE
Beautified Counting days and fixed a bug in it

### PR DESCRIPTION
**Pull request by predator-24**

### CODE REVIEW

**Comment by predator-24** [comment]
issue number #314

**Comment by predator-24** [comment]
@RaveenaBhasin, please have a look at this

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@predator-24, kindly avoid removing the explanation and the checkboxes mentioned in the pull request template.

**Comment by predator-24** [comment]
I'm really sorry @GowthamGoush about that, do i need to change something in pr

**Comment by GowthamGoush** [comment]
Yeah, @predator-24, you can look at the recently merged pull requests to get a fair idea.

**Pull request closed without merging**
