### PR TITLE
Twitter Data Streaming

### LINKED ISSUE #404: Twitter Data Streaming Using Python

### PR DESCRIPTION
**Pull request by dhruv-varshney**
Fixes #404 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by dhruv-varshney** [comment]
@GowthamGoush when I was assigned with this issue it was level 3 . But now it changed to level 2. may i get to know why??

**Comment by GowthamGoush** [comment]
So the label mentioned in the issue is tentative, and it's there to give a fair idea. The label assigned in PRs matters, and it will be awarded based on various parameters, including time taken to solve the code, complexity of the problem and so on.

**Comment by dhruv-varshney** [comment]
ok, But I guess this code is more difficult since this project also involves big data (Kafka). But ya alloting points will depend on the mentor. Thanks for assigning me this task.

**Pull request merged**
