### PR TITLE
FIXES #430 FLAPPY BIRD GAME ADDED

### LINKED ISSUE #430: Want to add Flappy Bird game in Pyhton
@Tejas1510 @RaveenaBhasin please assign me this under LGM-SOC'21

### PR DESCRIPTION
**Pull request by DhirajChauhan40**
#430 
FLAPPY BIRD GAME
image

Made the flappy bird game using pygame library of python.
It has many features.
checkout

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Awesome job @DhirajChauhan40, just add the readme as per #145 to get merged.

**Comment by GowthamGoush** [comment]
Also, add the keyword "Fixes" before the issue number.

**Comment by DhirajChauhan40** [comment]
@GowthamGoush im new to this so can i ask about what is those checks(cpp) and all
and why it is failing
i will upload readme file asap

**Comment by RaveenaBhasin** [comment]
@DhirajChauhan40 The source code for the game is copied directly from https://www.codewithharry.com/videos/python-tutorials-for-absolute-beginners-122 with only changes in the background image and screen size.
We appreciate it if you kindly write scripts on your own as in this way you will be unable to learn anything while contributing.
Thanks for your valuable time, hoping to have the next script from you soon.

**Comment by DhirajChauhan40** [comment]
@RaveenaBhasin @GowthamGoush I followed that video to learn the game, but I didn't understand some parts so I copied from his source
but next time I will make sure I won't do that without giving credit to them 
I'm sorry for that

**Comment by GowthamGoush** [comment]
> @RaveenaBhasin @GowthamGoush I followed that video to learn the game, but I didn't understand some parts so I copied from his source
> but next time I will make sure I won't do that without giving credit to them
> I'm sorry for that

We are happy that you tried to learn, but it would have been great to just implement what you learned instead of copying the code.

**Pull request closed without merging**
