### PR TITLE
#492 Added Ping Pong Game

### LINKED ISSUE #492: Ping Pong Game
An AI based Ping-Pong game in python with a GUI, each player controls a paddle in the game by dragging it vertically across the screen’s left or right side. Players use their paddles to strike back and forth on the ball.

### PR DESCRIPTION
**Pull request by Rutuj-Runwal**
**This PR is corresponding to issue #492, it adds a new GUI based Ping-Pong Game with 2 player support as suggested in the issue.**

## Output:
Sample_Output

Fixes #492 
## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by Rutuj-Runwal** [comment]
@RaveenaBhasin @GowthamGoush Please Review

**Comment by RaveenaBhasin** [comment]
@Rutuj-Runwal Update readme as per #145

**Comment by Rutuj-Runwal** [comment]
> @Rutuj-Runwal Update readme as per #145

Updated

**Comment by Rutuj-Runwal** [comment]
> @Rutuj-Runwal Update readme as per #145

Updated

**Pull request merged**
