### PR TITLE
Fix #895 Added Table Scrapper (in Python using Web Scrapping)

### LINKED ISSUE #895: Table Scrapper (in Python using Web Scrapping)
**Is your feature request related to a problem? Please describe.**
Sometimes while creating a script ,project or system we need some data from a website or a web page which may be in the form of tables, also going through this repository I found various scripts in which a .CSV or a list of data were required in order for them to work Ex NIRF Ranking System,Indian Food,etc .It will be really time consuming and hectic copying data or even copying or typing the same table in your local system manually.

**Describe the solution you'd like**
So for this i would like to make a python script file which will help users to scrap tables from the web pages and automatically convert them to .CSV files so that it can be used in the projects or databases.This will include the following
* Entering the URL
* Entering the required information to scrap out tables
* Converting them to DataFrame
* Finally converting them to .CSV file

<B>Advantages of this script<B/> 
* It will be really efficient to scrap out tables in just seconds.
* It will save a lot of time.
* Users can also get the updated tables which they could not get if they copy or manually enter data.
* Programmers can get to know more about "WEB SCRAPPING" from this script.

### PR DESCRIPTION
**Pull request by Rajulmahto21**
## Explanation

* Sometimes while creating a script ,project or system we need some data from a website or a web page which may be in the form of tables, also going through this repository I found various scripts in which a .CSV or a list of data were required in order for them to work Ex NIRF Ranking System,Indian Food,etc .It will be really time consuming and hectic copying data or even copying or typing the same table in your local system manually.
* So for this i have created a python script which will directly make an excel or a csv file just by entering some details .This will include the following
    * Entering the URL
    * Entering the required information to scrap out tables
    * Converting them to DataFrame
    * Finally converting them to .CSV file
  
Fixes #895 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.
# Some screen snips of the code,working and output :-

* 1
* 2
* 3table scrapping
* 4

### CODE REVIEW

**Comment by Rajulmahto21** [comment]
Made a Pull Request that fixes #895 ,added Table Scrapper (in Python using Web Scrapping)

**Comment by Rajulmahto21** [comment]
I am sorry for taking so long to make a PR for the issue actually i got busy in the ongoing exams.

**Comment by RaveenaBhasin** [comment]
> I am sorry for taking so long to make a PR for the issue actually i got busy in the ongoing exams.

That's completely ok, glad to see such great work.

**Comment by Rajulmahto21** [comment]
@RaveenaBhasin Thanks!!! 😇

**Pull request merged**
