### PR TITLE
Added script Video to Gif

### PR DESCRIPTION
**Pull request by saiharsha-22**
@Tejas1510 Solved issue #34 .

### CODE REVIEW

**Review by tripathyprateek — APPROVED** [review]

**Comment by tripathyprateek** [comment]
looks good to me. @Tejas1510 can you take a look at this.

**Comment by Tejas1510** [comment]
The code looks good 
I am merging the code

**Comment by saiharsha-22** [comment]
@Tejas1510 one small doubt all the merges which I have done it will be considered right ?

**Comment by Tejas1510** [comment]
I have sent a message to the organizer and they will be looking into that and as most of the participants had confusion they will give points

**Comment by saiharsha-22** [comment]
@Tejas1510 thank you

**Pull request merged**
