### PR TITLE
Added Any file to Pdf converter

### PR DESCRIPTION
**Pull request by suraj-singh12**
Added a python script that can convert txt, pptx, docx, and excel files to pdf files in seconds.
## Explanation

  
Fixes #:

## Checklist

- [ ] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [ ] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by GowthamGoush** [comment]
@suraj-singh12, kindly mention the issue number.

**Comment by suraj-singh12** [comment]
This adds a new project, doesn't fix any issue. Was contribution supposed to be fixing an issue. Kindly Pardon me, I wasn't informed so by my mentor.

**Comment by GowthamGoush** [comment]
> @GowthamGoush This adds a new project, doesn't fix any issue. Was the contribution supposed to be fixing an issue?
> Kindly Pardon me, I wasn't informed so by my mentor.

Of course, you've to link a pull request with an issue, and no mentor will be assigned personally to help you out. So always take a look at contribution guidelines before contributing.

**Comment by suraj-singh12** [comment]
ok.

**Pull request closed without merging**
