### PR TITLE
Cricbuzz live score added

### PR DESCRIPTION
**Pull request by Sudip704**
Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by Tejas1510** [comment]
@Sudip704 take the link as user input
Also, the Readme File Should Have proper input and output images

**Comment by Tejas1510** [comment]
@Sudip704 do you wish to work or should I assign someone else
The time limit has already been crossed

**Comment by Sudip704** [comment]
ok bhaiya aj zarur kar dunga bhaiya, mai jgec gaya tha registration form
jama karne islie nhi kar paya tha.

**Comment by Sudip704** [comment]
Bhaiya, assign it to someone else.

**Comment by Tejas1510** [comment]
@Sudip704 if you want some time I will give you
See ham koi race nahi dod rahe 
Mera main kam he ki tum open source sikh pao
So tension mat lo aaj ka pura din deta hu aaj khatam karlo
Tumhe sirf Readme File Add karni he

**Pull request closed without merging**
