### PR TITLE
Add Basic Calculator

### LINKED ISSUE #445: want to add Basic Calculator in python

### PR DESCRIPTION
**Pull request by rishabhrathore055**
## Explanation
 Add Basic Calculator in Python Programming Language
  
Fixes #:445

## Checklist

- [x] The PR title starts with "Fix #445 ".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by rishabhrathore055** [comment]
@GowthamGoush  Check It pls

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@rishabhrathore055, kindly check the changes that you have made. 
Also, make sure to:
    - Fill in the checkboxes.
    - Add the issue number properly.

**Comment by rishabhrathore055** [comment]
@GowthamGoush  now??

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@rishabhrathore055, consider raising a new pull request. Unfortunately, I could not see any changes.

**Pull request closed without merging**
