### PR TITLE
'how to' type qus using voice

### LINKED ISSUE #737: asking how to type questions
**Is your feature request related to a problem? Please describe.**
I want to add a feature in which the user can ask (using voice) **how to** questions. It uses the voice recognizer to process the voice command and then a library/API to get the answers of **how to** type questions. 

**Describe the solution you'd like**
I will be using python to add this feature with the help of voice recognizer api and a library for how to questions.

### PR DESCRIPTION
**Pull request by Umesh-01**
## Explanation
Added a feature to search **'how to'** type questions using voice. For this feature I have used speech recognition, pyttsx3  and pywikihow library. 
  
This fixes #737 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by RaveenaBhasin** [comment]
@mehabhalodiya @GowthamGoush Is there a need to add screenshots of this script for CLI and Pycharm both? According to me adding one of them would be sufficient.

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya @GowthamGoush Is there a need to add screenshots of this script for CLI and Pycharm both? According to me adding one of them would be sufficient.

Any one of them will be good to go !

**Comment by RaveenaBhasin** [comment]
@Umesh-01 Kindly remove the screenshots of CLI ouput.

**Comment by GowthamGoush** [comment]
> Any one of them will be good to go !

+1

**Comment by Umesh-01** [comment]
> @Umesh-01 Kindly remove the screenshots of CLI ouput.

@RaveenaBhasin @GowthamGoush now check it... 🙂

**Comment by Umesh-01** [comment]
and pls close the issues #357 and #362 
my PRs are already merged but the issues are still open don't know why...

**Pull request merged**
