### PR TITLE
Desktop_notifier

### PR DESCRIPTION
**Pull request by Ayush7614**
Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by Ayush7614** [comment]
@Tejas1510 this pull is for issue no #142

**Comment by Tejas1510** [comment]
@Ayush7614 stash all your commit in a single commit

**Comment by Ayush7614** [comment]
so @Tejas1510 plss close this

**Comment by Ayush7614** [comment]
@Tejas1510 plss review it

**Pull request merged**
