### PR TITLE
Fix #904 Updated readme

### LINKED ISSUE #904: Updating readme
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. the technologies used logo are too big which doesn't look good 

**Describe the solution you'd like**
A clear and concise description of what you want to happen the logos  images can be replaced with original logos an===with link of any official language website or study website through which user can understand about the language like w3 resources , pepcoding , for java javapoint 

**Describe alternatives you've considered** Beside their is lot which can be change to make readme look nice as no need of putting languages name  two time in badges and text , font of repo is too big , Hacking script logo can be edited by removing white background to make it look more relevant than like adding a image .

**Additional context**
Sorry to say but whoever made this New issue template he/she just copied from other project because it is totally similar to  another project.

### PR DESCRIPTION
**Pull request by Komal-99**
## Explanation

  
Fixes #904

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by RaveenaBhasin** [comment]
@Komal-99 Kindly correct the spelling of Introduction

**Comment by Komal-99** [comment]
> @Komal-99 Kindly correct the spelling of the Introduction. Undo the changes you have made in the logo after the Join official slack channel line.
> Update the alignment here.
> Screenshot (2621)
Oh okay . So you mean you need the earlier logo with white background only?

**Comment by RaveenaBhasin** [comment]
> > @Komal-99 Kindly correct the spelling of the Introduction. Undo the changes you have made in the logo after the Join official slack channel line.
> > Update the alignment here.
> > Screenshot (2621)
> > Oh okay . So you mean you need the earlier logo with white background only?

Yes

**Comment by Komal-99** [comment]
done kindly check

**Pull request merged**
