### PR TITLE
Added Chrome Dino Automation Script and Readme file

### PR DESCRIPTION
**Pull request by anubhab1710**
Fulfilled issue no: #254 

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:
This PR has the folder Chrome Dino Automation containing the Python Script and descriptive Readme.md file for implementing the script (as per the assigned issue)

#### Added
1. Main script code (in .py format)
2. Readme.md file for description of the script

### CODE REVIEW

**Comment by Tejas1510** [comment]
@anubhab1710 please stash all your commits

**Comment by anubhab1710** [comment]
> @anubhab1710 please stash all your commits

How do I do that can you please guide?

**Comment by Tejas1510** [comment]
@anubhab1710 This will help you https://git-scm.com/book/en/v2/Git-Tools-Stashing-and-Cleaning

**Comment by Tejas1510** [comment]
An easy way out is like you close this PR and make a new PR by adding all thing in a single commit

**Pull request merged**
