### PR TITLE
User

### PR DESCRIPTION
**Pull request by richabh456**
Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by richabh456** [comment]
please review my pr

**Comment by RaveenaBhasin** [comment]
@richabh456 Can you tell it is related to which issue?

**Comment by richabh456** [comment]
it is related to issue no #320

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Hey, @richabh456, kindly consider removing changes made to inappropriate folders.

**Comment by richabh456** [comment]
@GowthamGoush sorry sir i didn't understand

**Pull request closed without merging**
