### PR TITLE
TODO

### LINKED ISSUE #91: Todo List in Javsscript
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Todo List with Javascript

### PR DESCRIPTION
**Pull request by devmalik7**
Fixes #91 

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by Tejas1510** [comment]
@devmalik7 can you add a screenshot so it will be easy to understand about the app

**Comment by devmalik7** [comment]
@Tejas1510 I have already added a Screenshot In the README.md  file.

**Comment by Tejas1510** [comment]
@devmalik7 No add it here so I may be able to see
You just have to copy paste the image

**Comment by devmalik7** [comment]
@Tejas1510 here are the screenshots

image

image

**Pull request merged**
