### PR TITLE
Fixes #574 : Added Movie Info script which show information of movies through API

### LINKED ISSUE #574: Want to add a script to get information of movies using API in JavaScript  under LGMSOC'21
**Describe the solution you'd like**
``I want to make a script which can show the user all the information about the move according to the given search query using API ``

### PR DESCRIPTION
**Pull request by Pradhuman-singh5**
## Explanation

  
Fixes #574 

``Added files which can show the movie information with the help of API``

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by Pradhuman-singh5** [comment]
@amanjha8100  Sir,  check this PR  and let me know in case of any suggestions

**Comment by RaveenaBhasin** [comment]
@Pradhuman-singh5 Kindly update the readme acc. to #145

**Comment by Pradhuman-singh5** [comment]
@RaveenaBhasin , Done check it out

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
