### PR TITLE
Added Text Editor in Python Scripts

### LINKED ISSUE #879: Text Editor
Language : Python

In this script, will create an simple text editor using tkinter GUI,
In this application user have different option like
write anything
redo
undo
cut
copy
paste
can also find some text
save the open
open existing file

and many more options

### PR DESCRIPTION
**Pull request by akash435**
- A "Text Editor" is an a simple text editor created in python with tkinter gui.
- In this application, user have many options like, can open new file, open existing file, can do cut, copy and paste, can do undo and redo operation, can also search any word or text in the file.
- There are also other options like highlighting the particular line or not, changing the theme of the notepad (there are given 7 different themes in theme option).
- Also while searching any text, the searched text is highlighted with yellow color.
- Also on the bottom right corner, user can see the position of current cursor, in terms of line no. and column no.
- And many more options.
  
Fixes #879

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by akash435** [comment]
@RaveenaBhasin @GowthamGoush @mehabhalodiya , created a pr for adding Text Editor in Python scripts, please check it.

**Comment by UG-SEP** [comment]
> @RaveenaBhasin @GowthamGoush @mehabhalodiya , created a pr for adding Text Editor in Python scripts, please check it.

your project is really awesome nice work @akash435

**Comment by akash435** [comment]
> your project is really awesome nice work @akash435

Thanks @UG-SEP

**Comment by akash435** [comment]
@GowthamGoush @RaveenaBhasin @mehabhalodiya , please review my pr

**Review by GowthamGoush — APPROVED** [review]

**Pull request merged**
