### PR TITLE
updated random password generator.c

### PR DESCRIPTION
**Pull request by harsh6768-svg**
Just updated the SRAND function to take distinct values

Fixes #

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:
<Using SRAND function in an easier way and decreasing time of compilation>

### Change logs:

<just updated the SRAND function take distinct values of password>

### Fixed:

<No bugs just increased the efficiency>

### CODE REVIEW

**Comment by GowthamGoush** [comment]
@harsh6768-svg, could you please the issue which is being fixed here?

**Comment by harsh6768-svg** [comment]
@GowthamGoush with removing pid which is always unique time of compilation just increases for few second so just removed the pid part otherwise everything is same

**Comment by GowthamGoush** [comment]
> @GowthamGoush with removing pid which is always unique time of compilation just increases for few second so just removed the pid part otherwise everything is same

@harsh6768-svg actually, when a person raises a pull request, he/she has to mention the issue they want to fix. So you have to just mention the issue id, for example, "#931".

**Comment by harsh6768-svg** [comment]
Sorry @GowthamGoush I forget to mention issue no #306

**Comment by GowthamGoush** [comment]
> Sorry @GowthamGoush I forget to mention issue no #306

Alright, no problem, @harsh6768-svg, but just a humble request, please get the issue assigned before you can start working on it.

**Comment by harsh6768-svg** [comment]
@GowthamGoush why analyze section is failing can you help???

**Comment by GowthamGoush** [comment]
> @GowthamGoush why analyze section is failing can you help???

Don't worry about it much as of now.

**Pull request merged**
