### PR TITLE
Sentiment Classifier #483

### LINKED ISSUE #483: Sentiment Classifier in Python
A Sentiment Classifier is a program which will detect how positive or negative each tweet is. Also I will add a csv file, which contains columns for the Number of Retweets, Number of Replies, Positive Score (which is how many happy words are in the tweet), Negative Score (which is how many angry words are in the tweet), and the Net Score for each tweet. At the end, I will upload the csv file to Excel or Google Sheets, and produce a graph of the Net Score vs Number of Retweets.

### PR DESCRIPTION
**Pull request by ishitakapoor26**
Fixes #483 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by ishitakapoor26** [comment]
@Tejas1510 @GowthamGoush pls review my pr.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Hey, wonderful work, but before merging this PR, please consider adding changes to readme as per #145.

**Comment by ishitakapoor26** [comment]
> Hey, wonderful work, but before merging this PR, please consider adding changes to readme as per #145.

@GowthamGoush Ya I got it but my program takes input as csv files which are attached as files to it, so how can I attach images of it ; file is too large and about output images it's already there. Other readme guidelines I have already followed.

**Comment by ishitakapoor26** [comment]
@GowthamGoush done changes.

**Pull request merged**
