### PR TITLE
Added Game #419

### LINKED ISSUE #419: Phrase Guessing Game in Python
Phrase Guessing Game in Python

### PR DESCRIPTION
**Pull request by ishitakapoor26**
Fixes #419 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, @ishitakapoor26, that was an outstanding work. It could be more amazing if you could add the images of the game in the readme as per #145.

**Comment by ishitakapoor26** [comment]
@GowthamGoush pls review i've added images to readme file.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Could you please fix the error in the readme? "\" needs to be replaced with "/".

**Comment by ishitakapoor26** [comment]
> Could you please fix the error in the readme? "\" needs to be replaced with "/".

okay

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
