### PR TITLE
Added Part Of Speech in Python

### LINKED ISSUE #679: Part Of Speech Calculator in Python
In this script, user first can enter enter any text or sentence or any paragraph.

and this script will tells us about the no. of part of speeches present in it.
eg, no. of noun, no. of adverb, adjective, verb, etc.

### PR DESCRIPTION
**Pull request by akash435**
Added Part of speech calculator in Python
In this application user can enter any text or sentence or paragraph, and will be able to get the count of each part of speech and what are they.
  
Fixes #679

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

Below are the screenshot of how application works,

### CODE REVIEW

**Comment by akash435** [comment]
@GowthamGoush @RaveenaBhasin , created a pr for adding part of speech calculator in Python script, please check it

**Comment by akash435** [comment]
@GowthamGoush , correct the typo, please check it.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Sorry, I didn't mention the typo in the readme. Please fix that as well.

**Comment by akash435** [comment]
corrected typo in readme also ,please check it.
And sorry for such typos.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
