### PR TITLE
Bounce Ball Game

### LINKED ISSUE #730: Bounce Ball Game
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### About
I would like to create a bouncing ball game using Python GUI in which there will be one bar at the lowest of window which can be moved left or right. The main goal of this game is to hit the targets and increase your score. 

### Do you want to work on this issue?
YES

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
- Added the "Bounce Ball Game" in Python Scripts.
- In this game, the user has to hit the bricks from the ball which will rebound after hitting the bar at the bottom, if the ball hits the bottom frame then the game will end.
- The bar can be moved using the left and right arrow key, the game can be paused using "Space Bar" and can be resumed by again pressing it
- I had added the splash screen which will last for 5 sec. & then the game will launch automatically.
- Added the logo to the game . 
  
Fixes #730 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

SCREENSHOTS:
Splash Screen GIF
Bounce Ball_SplashScreen

First Screen With Logo

Game Screen

Pause Screen

GameOver Screen

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please consider removing the changes added to the main readme file.

**Comment by Khushi-sharma07** [comment]
Sir, I don't know why these changes are made infact I didn't even touched the main readme file.
Sir should I delete this file from my pr?

**Comment by Khushi-sharma07** [comment]
Sir can you please recheck now. @GowthamGoush

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Since you've deleted the main readme, when I merge this PR, the readme remains deleted in the main repo as well.

**Comment by GowthamGoush** [comment]
> Sir, I don't know why these changes are made infact I didn't even touched the main readme file.
> Should I delete this file from my pr?
> Can you please tell what to do to remove the changes made in main readme file @GowthamGoush sir

Since you've made the commit for the readme much before committing your code, this commit for readme lies at the bottom of the tree. Because of which reseting the head is quite complex here.
Alright, what you can do now is, create a new branch and push only the commits concerned with your script. Remember you don't need to write the code again, just need to push to a new branch. Also, let me discuss with my fellow mentors and let you know if there is any other way around.

**Comment by Khushi-sharma07** [comment]
Okay sir i will try this

**Comment by Khushi-sharma07** [comment]
Sir I am trying this also and I will try to do as you said but sir if I fails. Closing this issue from your side is possible ? 
I will create a new issue before only.

**Comment by GowthamGoush** [comment]
> Sir I am trying this also and I will try to do as you said but sir if I fails. Closing this issue from your side is possible ?
> I will create a new issue before only.

So there is no need to create a new issue again. Just closing this PR would be fine but, hang on, I'll come back to you with an alternate solution if it exists.

**Comment by Khushi-sharma07** [comment]
Okay sir..thank you so much

**Comment by GowthamGoush** [comment]
> Okay sir..thank you so much

Hey, @Khushi-sharma07, if you know how to reset the head, then you may go ahead and do that. However, be careful while resetting your head. You might end up losing your work. Else, the above one could be an alternative.

Finally, feel free to call me by my name since I just a student 😅

**Comment by Khushi-sharma07** [comment]
Actually I don't know much about GitHub this is a very beginning of my journey in GitHub. Please can you do the other one option. 
Okay sure Gowtham nice to meet you.😊

**Comment by GowthamGoush** [comment]
> Actually I don't know much about GitHub this is a very beginning of my journey in GitHub. Please can you do the other one option.
> Okay sure Gowtham nice to meet you.😊

Alright, @Khushi-sharma07, since you are a beginner, this is the perfect place where you can learn. So don't worry much about the points, rather focus on what you can learn out of this program, which is much more valuable than swags. 
You may reach out to any of the mentors in case if you face any trouble.

**Comment by GowthamGoush** [comment]
There is one more way around, so you can copy/paste and commit the exact readme as in the repo, and there should be no changes found.

**Comment by Khushi-sharma07** [comment]
Okay yes I will do this

**Comment by Khushi-sharma07** [comment]
I had already deleted that changed file so now I will copy the main readme file nd commit it.. that's great.. thank you so much

**Comment by Khushi-sharma07** [comment]
I also want to know one thing that there are two readme file I think the updated one is "readme.md"

**Comment by Khushi-sharma07** [comment]
IMG_20210625_112739

These are the two files I could see in main repository. Can you please tell which one to copy?

**Comment by GowthamGoush** [comment]
`README.md` was the file that you've made the changes to, so just consider adding that alone.

**Comment by Khushi-sharma07** [comment]
Okay

**Comment by Khushi-sharma07** [comment]
I will do it just now please check it.

**Comment by Khushi-sharma07** [comment]
I had created it you can check it's exactly same as the main repository

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by GowthamGoush** [comment]
> I had created it you can check it's exactly same as the main repository

Hey, I really appreciate your patience.

**Comment by Khushi-sharma07** [comment]
Actually it's you who helped me a lot...thank you so much. Really nice meeting you and learn in your guidance.

**Pull request merged**
