### PR TITLE
New folder added for transfer of words

### PR DESCRIPTION
**Pull request by kumarjeetray**
## Explanation
 A folder is created which contain a server and a client file for transfer of information between two computers or a computer and a VM
  
Fixes #695 

## Checklist

- [ ] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [ ] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by kumarjeetray** [comment]
A folder is created which contain a server and a client file written in python for transfer of information between two computers or a computer and a VM

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly mention the issue number and modify the readme as per #145.

**Comment by kumarjeetray** [comment]
> 
> 
> Kindly mention the issue number and modify the readme as per #145.

Done. Please do check and let me know

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please follow the hierarchy of font size for heading and add images of the script.
Also, please mention the issue number.

**Comment by amanjha8100** [comment]
@kumarjeetray look into what @GowthamGoush has pointed out to, asap?

**Comment by GowthamGoush** [comment]
Since this script has been added in another PR, I'm closing this.

**Pull request closed without merging**
