### PR TITLE
Added Rock,Paper,Scissors game in java

### LINKED ISSUE #325: Want to add Rock, Paper, Scissors game in JAVA
Hey @Tejas1510 will you please assign me this issue under LGM-SOC'21 and also could you please add labels to it if possible??

### PR DESCRIPTION
**Pull request by mitali-1703**
## Explanation
Added Rock,Paper,Scissors game in java.
  
Fixes #325 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by mitali-1703** [comment]
@RaveenaBhasin @GowthamGoush plz review my PR and merge it adding labels to the merged PR..thnx

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly remove the irrelevant files.

**Comment by mitali-1703** [comment]
> Kindly remove the irrelevant files.

done @GowthamGoush

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
