### PR TITLE
Added javascript/MemoryGame aka guess the colors in correct order game #329

### LINKED ISSUE #329: Guess the colors in correct order Game
Hey, this is a very interesting game, where we generate random color ordering and player needs to guess the color from start 
till end in the correct order, else he looses the game. 

Screenshot (2)
Screenshot (3)
Screenshot (4)

### PR DESCRIPTION
**Pull request by predator-24**
Fixes #329 

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by GowthamGoush** [comment]
Could you please mention the issue that you have fixed?

**Comment by RaveenaBhasin** [comment]
@predator-24 Mention the related issue with every PR and update the readme acc. to #145

**Comment by predator-24** [comment]
sorry, about not mentioning related issue, it was #393

**Comment by GowthamGoush** [comment]
> sorry, about not mentioning related issue, it was #393

Well, this pull request is linked with #329. Anyway good job 👍

**Review by GowthamGoush — COMMENTED** [review]
Ready to be merged.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please consider removing the latest changes irrelevant to this pull request.

**Comment by predator-24** [comment]
Hey @GowthamGoush sorry I didn't got what you meant, I'm a newbie here

**Comment by GowthamGoush** [comment]
Alright, no worries, @predator-24. 

- This pull request is meant for just adding files or changes associated with the "Memory Game".
-  In the recent commit, you have added changes made for "Counting days".
- Now, you can resolve this by removing those commits for "Counting days". For adding changes for "Counting days", create a new branch and a new pull request.

**Comment by predator-24** [comment]
@GowthamGoush and @RaveenaBhasin i will close this pr for now firstly you guys merge my counting days request and I'll post this pr again

**Pull request closed without merging**
