### PR TITLE
add auto assign issue #199

### LINKED ISSUE #199: [Github Action] Auto Assign issue
**Is your feature request related to a problem? Please describe.**

A lot of times contributors have to wait for the project maintainers to assign them a particular issue so that they can make the pull request or maybe start working on it. It would be better if better if we can automate this assigning task.

**Describe the solution you'd like**
Anyone could auto assign the issue using a keyword or special command. We can use github actions available for this.

### PR DESCRIPTION
**Pull request by imakash3011**
Fixes #199

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:
- Added GitHub action for auto assign issue.

### Change logs:
- Added AutoAssignIssue.yml file

- GitHub Action for auto assign issue.

### CODE REVIEW

**Comment by imakash3011** [comment]
## Inputs

| Parameter    | Required | Description                                                                |
| ------------ | -------- | -------------------------------------------------------------------------- |
| `repo-token` | true     | The GITHUB_TOKEN, needed to update the Issue.                              |
| `assignees`  | true     | Comma separated list of user names. Issue will be assigned to those users. |

follow above command to auto assign issue.

**Comment by imakash3011** [comment]
what to do some checks are failing @Tejas1510 ?

**Review by atarax665 — COMMENTED** [review]
We are looking for an action that assigns issue to anyone who comments on the issue using a keyword like '''/assign''' or something similar.

**Comment by imakash3011** [comment]
@atarax665  could you please tell me which GitHub action should i use.

**Pull request closed without merging**
