### PR TITLE
added music player game

### LINKED ISSUE #140: A vanilla Js music player
it's a music player that will play sound as you click on it and will also show animations as you click on any of the tiles that play the music

### PR DESCRIPTION
**Pull request by Sloth-Panda**
Fixes #140 

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:

It's a music player made using html, css and vanilla js has some nice animation when you click on the tiles

### Change logs:

Updated the readme for this pr

### Fixed:

No bug fixes were donw with this pr

### Snapshot:

Screenshot (68)

On clicking those tiles it throws these spehircal balls of different colors as per the tile color in a triangular path-> 
Screenshot (73)

@Tejas1510 has made the required changes you can check  out

### CODE REVIEW

**Comment by Tejas1510** [comment]
Add a Readme File in the format Provided

**Comment by Sloth-Panda** [comment]
@Tejas1510  can you please check this has made the required changes

**Comment by Tejas1510** [comment]
Where is your readme file 
I am not able to find it in your PR

**Comment by Sloth-Panda** [comment]
oh sorry , did you ask for readme of the game?

**Comment by Sloth-Panda** [comment]
now you can check this out @Tejas1510

**Pull request merged**
