### PR TITLE
dice simulator in js

### LINKED ISSUE #106: Dice Rolling Simulator using Python-random
* Aim
Dice Rolling Simulator using Python-random

* Details
In this Script we will create a classic rolling dice simulator with the help of basic Python knowledge. Here we will be using the random module since we randomize the dice simulator for random outputs.

### PR DESCRIPTION
**Pull request by pritamp17**
Fixes #106

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:
the dice simulator in javascript

### Snapshot:
refresh-1

### CODE REVIEW

**Review by atarax665 — COMMENTED** [review]
Format your README according to the README template given in #145

**Comment by pritamp17** [comment]
@atarax665 I have made changes in Readme.

**Comment by Tejas1510** [comment]
@pritamp17 Please follow the Readme Format Provided
Provided proper instruction for running the script starting from cloning the repo to running the script
Input and Output Images are also missing

**Comment by pritamp17** [comment]
@Tejas1510 I made the changes in Readme.

**Pull request merged**
