### PR TITLE
tic tac toe game in java

### LINKED ISSUE #413: Want to make a Tic Tac Toe game using Java
**Is your feature request related to a problem? Please describe.**
As we know for fun tic-tac-toe game is not bad till now. It is famous even now.😄 So, why to not implement in **Java**...

**Describe the solution you'd like**
I want to create a **tic-tac-toe** game using **Java** programming.

### PR DESCRIPTION
**Pull request by Umesh-01**
## Explanation
I have created a Tic Tac Toe game using java. Also added README.md file and images to explain about it.
  
This fixes #413 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, great job! 
Before merging this kindly mention the issue number right next to "Fixes" to auto-close the issue when the PR is merged.

**Comment by Umesh-01** [comment]
> Hey, great job!
> Before merging this kindly mention the issue number right next to "Fixes" to auto-close the issue when the PR is merged.

It's already mentioned or did u mean I should remove ISSUE and write only issue number before it??

**Comment by Umesh-01** [comment]
done @GowthamGoush sir 🙂

**Comment by GowthamGoush** [comment]
> done @GowthamGoush sir 🙂

OMG, feel free to call me Gowtham. I'm a student just like you.

And I hope you understood the reason why I asked you to make the above change.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by Umesh-01** [comment]
> > done @GowthamGoush sir 🙂
> 
> OMG, feel free to call me Gowtham. I'm a student just like you.
> 
> And I hope you understood the reason why I asked you to make the above change.

yes, I got it... 😄

**Pull request merged**
