### PR TITLE
Added Regex Checker in Python Scripts

### LINKED ISSUE #1030: Regex Checker
Language : Python

In this script, will create an application using tkinter GUI,

In this application user will be able to check whether a given regex is correct or not.

here will ask user to enter any regex and application will tell the user that regex is correct/valid or not.

### PR DESCRIPTION
**Pull request by akash435**
- A "Regex Checker" is an application created in python with tkinter gui.
- In this application, user will be able to check the correctness of the any regex expression.
- for implementing this regex checker, using the compile method in re library of python.
  
Fixes #1030

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
Enhancement:
Add `Regular Expression cheatsheet` button and a list like below. Can you?
regex

**Comment by akash435** [comment]
@mehabhalodiya , means i need to create a button "Regular Expression cheatsheet", clicking on which opens this given cheatlist.
is it?

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya , means i need to create a button "Regular Expression cheatsheet", clicking on which opens this given cheatlist.
> is it?

Yes!

**Comment by akash435** [comment]
> > @mehabhalodiya , means i need to create a button "Regular Expression cheatsheet", clicking on which opens this given cheatlist.
> > is it?
> 
> Yes!

I can do that , can i update it?

**Comment by akash435** [comment]
@mehabhalodiya , done, with the enhancement, please check it.

**Pull request merged**
