### PR TITLE
Added Snake game in JS

### PR DESCRIPTION
**Pull request by mitali-1703**
Fixes #

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:
I have added a snake game made using pure HTML, CSS and JS.

### Fixed:
PR to Issue no #382

### CODE REVIEW

**Comment by mitali-1703** [comment]
Hey @Tejas1510 can you tell me how can i pass the rest 2 test cases as well?

**Comment by mitali-1703** [comment]
@RaveenaBhasin please review this PR.

**Comment by RaveenaBhasin** [comment]
@mitali-1703 Add readme file

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Could you please add readme as per #145?

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by mitali-1703** [comment]
@RaveenaBhasin @GowthamGoush done with adding the readme file.

**Pull request merged**
