### PR TITLE
adventure game updated

### LINKED ISSUE #607: Text Based Adventure game using Python

### PR DESCRIPTION
**Pull request by dhruv-varshney**
Fixes #607 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

I made the required changes hope you like it

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Could you please add the "Librarires required" section in the readme?

**Comment by dhruv-varshney** [comment]
@GowthamGoush I just used a random module for the coin toss (0-head 1-tail). other than that no other library i used. is it okay to write a random library?

**Comment by GowthamGoush** [comment]
> @GowthamGoush I just used a random module for the coin toss (0-head 1-tail). other than that no other library i used. is it okay to write a random library?

Yeah, that's fine.

**Comment by dhruv-varshney** [comment]
ok i will write it @GowthamGoush

**Review by dhruv-varshney — COMMENTED** [review]
I added module used section in readme file

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
