### PR TITLE
Added Unscramble Word Game in Python

### LINKED ISSUE #620: Unscramble the Word in Python
Want to add this under in Python scripts.

In this the player will be given some unscrambled games, and need to write the correct word corresponding to each one of them.
And finally will be showing the result for their performance.

below is the screenshot of main window how it looks like,

### PR DESCRIPTION
**Pull request by akash435**
Fixes #620

 - Added Unscramble Word Game in Python Script.
 - In this game the player will be given, 20 unscrambled  word one by one and player needs to answer the corrected  word for each one of them.
 - Also there are only 20 Lives, if  player completes this 20 Lives, the game will over.
 - And as soon as given overs, the player will be able to see his/her score and status of how many answer skipped, given correct and wrong answer.

## Checklist

- [x] The PR title starts with "Fix #620".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [ ] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

Below are some screenshots for game,

### CODE REVIEW

**Comment by akash435** [comment]
@RaveenaBhasin @GowthamGoush , created a pr for adding Unscramble Word Game in Python Scripts, please check it.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by GowthamGoush** [comment]
Kindly check all the checkboxes next time.

**Comment by akash435** [comment]
ok, i will

**Comment by akash435** [comment]
Can you please check it is not labelled.

**Pull request merged**
