### PR TITLE
Create pythonProgramToCheckIpDetails

### PR DESCRIPTION
**Pull request by aryan040501**
It uses Ip Geolocation JSON and has about 10000 request/month limit.

Fixes #

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:

I have added a python program to check the details of IP address which a user can input.

### Change logs:

User can input IP address to check details

if user doesn't input anything, it checks the current users IP address automatically

### Fixed:

PR to Issue no #220 

### Snapshot:

It is a short script, completely new.

### CODE REVIEW

**Comment by Tejas1510** [comment]
Add a proper readme file as mentioned in #145 
Else the code is good to merge

**Comment by aryan040501** [comment]
> Add a proper readme file as mentioned in #145
> Else the code is good to merge

Okay Sir, Thanks a lot. Will do the needful

**Comment by aryan040501** [comment]
> Add a proper readme file as mentioned in #145
> Else the code is good to merge

I have added a readme

**Comment by Tejas1510** [comment]
Good Work @aryan040501

**Comment by aryan040501** [comment]
> Good Work @aryan040501

Thanks a lot Sir, It was my first PR in SWOC and Open Source.

**Comment by Tejas1510** [comment]
Congrats @aryan040501 on starting your open source journey 
A lot more to come from you 😊

**Pull request merged**
