### PR TITLE
Insect-catch-game

### PR DESCRIPTION
**Pull request by Ayush7614**
Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by Ayush7614** [comment]
This pull is for issue no #90 plss review it @tripathyprateek

**Comment by Tejas1510** [comment]
@Ayush7614 there are large no of commits
Please Stash them all in one Single Commit

**Comment by atarax665** [comment]
> This pull is for issue no #90 plss review it @tripathyprateek

Please fill the PR template first.

**Review by atarax665 — CHANGES_REQUESTED** [review]
Remove files related to ```Todo-List```, they are irrelevant to this PR.

**Comment by Tejas1510** [comment]
@tripathyprateek there is some confusion
You look at this PR and merge when you find it is suitable

**Comment by tripathyprateek** [comment]
> @tripathyprateek there is some confusion
> You look at this PR and merge when you find it is suitable

You talking about the checks failing?

**Comment by Ayush7614** [comment]
@Tejas1510 plss close this pull request beacuse this was create many problems for me

**Pull request closed without merging**
