### PR TITLE
Create CoffeeMachine

### LINKED ISSUE #549: Coffee Machine In Java Langauge
**Is your feature request related to a problem? Please describe.**
I want to contribute a code in java for coffee machine.

**Describe the solution you'd like**
A code in Java 

Hey @Tejas1510 please assign me this.

### PR DESCRIPTION
**Pull request by rahulsrivastava1**
## Explanation
  
Fixes #549 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly add a readme as per #145.
Also, add a short explanation and check all the checkboxes.

**Comment by rahulsrivastava1** [comment]
@GowthamGoush Hey Sir, i have updated the readme.md files including screenshots . please review

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by GowthamGoush** [comment]
> @GowthamGoush Hey Sir, i have updated the readme.md files including screenshots . please review

Hey, feel free to call me Gowtham 😅

**Comment by rahulsrivastava1** [comment]
hehe  sure @GowthamGoush , i want one more code to add...the chatty bot...where user will be first give their name and some inputs and the program will find their age... can i open pull request for this?

**Pull request merged**
