### PR TITLE
Moving Train Animation in C++ (#714)

### PR DESCRIPTION
**Pull request by Jyoti6828**
MOVING TRAIN ANIMATION C++ #714
        - This program is written in c++ where a train is moving using graphics.
	- This script is going to use graphics.h header file to move train.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@Jyoti6828, kindly update the readme according to #145. Also, consider removing the extra spaces from the main CPP file.

**Comment by Jyoti6828** [comment]
Okay ...I will do that.

**Comment by Jyoti6828** [comment]
Updates are done.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Hey, @Jyoti6828, there is a dedicated folder for C++. Please consider adding your script inside it.

**Comment by Jyoti6828** [comment]
How I can add my script in that folder ?

**Comment by GowthamGoush** [comment]
Direct copy/paste in there.

**Comment by Jyoti6828** [comment]
And then again I have to send pull request, right?

**Review by GowthamGoush — COMMENTED** [review]
Alright, now you may remove those redundant files.

**Comment by Jyoti6828** [comment]
Done.

**Comment by GowthamGoush** [comment]
You've removed the files from the C++ directory. Would you please undo that and remove these files which exist now?

**Comment by Jyoti6828** [comment]
Really sorry for that, Now im done with corrections. Please check it.

**Review by GowthamGoush — COMMENTED** [review]
One last step, consider moving the `ScreenShots.pdf` to your script directory.

**Comment by GowthamGoush** [comment]
It is not feasible to do from my side as well.

**Comment by Jyoti6828** [comment]
Now what should I do?

**Comment by GowthamGoush** [comment]
You may consider creating a new PR.

**Comment by Jyoti6828** [comment]
Sure I will do that.

**Pull request closed without merging**
