### PR TITLE
Added Htmltopdf Generator

### LINKED ISSUE #23: [Python][JS]HTML to PDF converter
Make a script which upon running converts any HTML page to PDF and stores it on the local machine. 

Can be made using the PDFKit library.

### PR DESCRIPTION
**Pull request by ckmganesh**
Fixes #23 - Added the require Htmltopdf using python. Also attached some outputs for reference

### CODE REVIEW

**Comment by tripathyprateek** [comment]
Hi @ckmganesh awesome job. Could you please add a requirements.txt file for anyone using this script to download the packages used. 

Also please share a screenshot of how the script is up and running for you. Also I will merge this after 5th of January so that your PR counts towards the leaderboard. Meanwhile, please do the requested changes :)

**Review by tripathyprateek — CHANGES_REQUESTED** [review]
Add requirements.txt file.

**Comment by ckmganesh** [comment]
All the requested changes are added.Please check it now

**Comment by Tejas1510** [comment]
@ckmganesh nice work
@ckmganesh all images should be in folder named images and always add a readme file which clearly tell what the project is how to run the project input and output SCREENSHOTS with proper description

**Comment by ckmganesh** [comment]
Requested updates are added. Please check.

**Review by tripathyprateek — APPROVED** [review]
Looks good to me. Approving. @ckmganesh will merge it on 5th January so that your contribution is counted. @Tejas1510 approve if it looks good.

**Review by Tejas1510 — COMMENTED** [review]
@ckmganesh The Code looks good to me
Just your readme is lagging input and output images just add that and your code is good to merge

**Comment by ckmganesh** [comment]
.



> Looks good to me. Approving. @ckmganesh will merge it on 5th January so that your contribution is counted. @Tejas1510 approve if it looks good.

Sure Thanks :)

**Comment by ckmganesh** [comment]
> @ckmganesh The Code looks good to me
> Just your readme is lagging input and output images just add that and your code is good to merge

Readme file updated with requires input and output screenshots.

**Comment by Tejas1510** [comment]
Good Work @ckmganesh 
We will merge your work on 5 Jan
Till then you can work on other issues

**Comment by ckmganesh** [comment]
Thanks.
Yeah Sure :)

**Comment by ckmganesh** [comment]
I've added the Website Status Checker. Please check

**Pull request merged**
