### PR TITLE
Brick Breaker Game 

### LINKED ISSUE #447: Brick Breaker Game
Title: Brick Breaker Game

LGM-SOC'21: Participant

Description: I would like to Implement Python libraries to create this game. Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Jagannath8**
##Title
Brick Breaker Game 

## Explanation
Using the paddle to move along the screen, the player hits the ball that can touch the bricks and destroy them. 
Player have to destroy all the bricks to win the game.
  
Fixes #447 

##Checklist
- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, @Jagannath8 amazing work. Before merging this, could you please consider adding those checkboxes present while raising the pull request?

**Comment by Jagannath8** [comment]
> Hey, @Jagannath8 amazing work. Before merging this, could you please consider adding those checkboxes present while raising the pull request?

Done @GowthamGoush

**Comment by GowthamGoush** [comment]
Alright, great. Just make sure not to add any changes to the PR template.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
