### PR TITLE
 #513 Adding PIP upgrade script

### LINKED ISSUE #513: PIP upgrade automation
**Is your feature request related to a problem? Please describe.**
You can upgrade PIP version just by running the script, no need to open cmd prompt and write the command.

**Describe the solution you'd like**
A python automated script implemented in tkinter framework.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by hr1shu**
## Explanation 

Fixes #513 :
   Added the script as assigned.

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Great job, @hr1shu.
Before merging this, kindly mention the issue number and the "fixes" keyword in this PR's initial comment.

**Comment by hr1shu** [comment]
Done!!!

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by GowthamGoush** [comment]
> Done!!!

Actually, I've added the necessary changes to the comment. Have a look and make sure to follow these in your upcoming PRs.

**Pull request merged**
