### PR TITLE
Added Color Generator

### LINKED ISSUE #397: Want to Add color code generator/picker in React Js

### PR DESCRIPTION
**Pull request by atharva21-stack**
Fixes #397

### Checklist:
- [X] My branch is up-to-date with upstream/master branch.

### Description:
Added color code generator/picker in React Js

### Change logs:
Added Color Generator
Added Color Picker

### CODE REVIEW

**Comment by RaveenaBhasin** [comment]
@atharva21-stack Kindly mention the related issue and add a readme file.

**Comment by atharva21-stack** [comment]
@RaveenaBhasin I've made the desired changes , have a look.

**Comment by RaveenaBhasin** [comment]
@atharva21-stack Kindly add the required images in the readme file.

**Comment by atharva21-stack** [comment]
@RaveenaBhasin I've have added the required images in the Readme

**Comment by mehabhalodiya** [comment]
@atharva21-stack Kindly resolve merge conflicts!

**Pull request closed without merging**
