### PR TITLE
CRICBUZZ scraper

### PR DESCRIPTION
**Pull request by Ayush7614**
Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by Ayush7614** [comment]
@Tejas1510 plsss review it this pull is for issue no #181

**Comment by Tejas1510** [comment]
@Ayush7614 you have directly copied the code from here https://github.com/divyranjan17/Python-Web-Scraping/blob/master/scraping.py
I have already said copy-pasting won't solve the purpose of open source

**Comment by Ayush7614** [comment]
Okk @Tejas1510 you really like it i am just copying the code from that repo sir i am promise i am even dont know this repo that you are mentioning in above but you say i copied it i will see you the screenshots of that in which i will make the program and see you the output and even i will say i will not copied from that but okk i will again make and see you with the output Yes one thing i also say that i will take help from GFG for the program but i didn't copy the program

**Comment by Tejas1510** [comment]
@Ayush7614 how can both code match exactly the same
See I am here to guide you to make you a better developer if you copy or not that's depends on you and you are not going to learn if you copy 
No worries consider this as a learning and work on other issues
Happy Coding

**Pull request closed without merging**
