### PR TITLE
Added a script to get map of any city

### LINKED ISSUE #438: Python Script to get a map of any location.
This python script will get the map of the location provided by the user.
@Tejas1510 @RaveenaBhasin Can you assign me this issue under LGM -SOC'21.

### PR DESCRIPTION
**Pull request by Paras0-7**
## Explanation

Added a python script that will get the map of the city provided to it.
  
Fixes #438

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, nice work, but could you please consider adding an output image?

**Comment by GowthamGoush** [comment]
@amanjha8100, could you please look at this regarding the label to be assigned?

**Comment by Paras0-7** [comment]
> Hey, nice work, but could you please consider adding an output image?

Thanks @GowthamGoush, I added the output image too.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
There is a minor typo error in the readme. Could you please retake some moment to fix it?

**Comment by Paras0-7** [comment]
> There is a minor typo error in the readme. Could you please retake some moment to fix it?

Hey @GowthamGoush I checked the readme file there were no typo errors.

**Comment by Paras0-7** [comment]
> > There is a minor typo error in the readme. Could you please retake some moment to fix it?
> 
> Hey @GowthamGoush I checked the readme file, there were no typo errors.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
One of the images in the readme isn't visible. Please have a check on that.

**Comment by Paras0-7** [comment]
> One of the images in the readme isn't visible. Please have a check on that.

@GowthamGoush , fixed the issue.

**Comment by Paras0-7** [comment]
> > One of the images in the readme isn't visible. Please have a check on that.
> 
> @GowthamGoush , fixed the issue.

Hey @GowthamGoush  could you please review it, I fixed the issue.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
