### PR TITLE
Fix #489 Calculator reinvented using js 

### LINKED ISSUE #489: Want to reinvent the js calculator present in the js folder cause it's totally broken
**Is your feature request related to a problem? Please describe.**
It doesn't work properly, the past inputs are not getting cleared and the calculator is tiny. The '%' acts like mod which calculators don't use

**Describe the solution you'd like**
I will change the design and remove the bugs and present a better one for the project.

### PR DESCRIPTION
**Pull request by Saup21**
## Explanation

This is a script for an online calculator.

  
Fixes #489

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Hey, @Saup21, your work is elegant, but you could have added these changes to the pre-existing folder for the calculator, right? I heartily appreciate your efforts but consider adding them to the pre-existing folder.

**Comment by GowthamGoush** [comment]
Also, mention the issue number right next to "Fixes".

**Comment by Saup21** [comment]
Fine I'll do it then and I'm not going to change the pre-existing folder name then.

**Comment by GowthamGoush** [comment]
> Fine I'll do it then and I'm not going to change the pre-existing folder name then.

The basic idea is to make sure not to have any duplicate scripts even though they differ by design and other things.

**Comment by Saup21** [comment]
I have changed the directory like you said.

**Review by GowthamGoush — APPROVED** [review]
Alright, thanks for the patience, @Saup21.
Ready to be merged.

**Pull request merged**
