### PR TITLE
File Transfer

### LINKED ISSUE #727: File Transfer
Is your feature request related to a problem? Please describe.
It is very difficult to transfer a file from a normal window to virtual machine as it does not support copying of files.
Describe the solution you'd like
We will use the concept of socket programming to make this happen.

### PR DESCRIPTION
**Pull request by kumarjeetray**
## Explanation:
  - This program helps in transfer of a file from one computer to another computer or VM in the same computer using the   
 concept of ports and sockets
  
Fixes #727 

## Checklist

- [X] The PR title starts with "Fix #issue_number".  
- [X] My branch is up-to-date with the main branch.
- [X] The PR does not contain any unnecessary auto-generated code.
- [X] The PR does not break any part of the existing code.
- [X] The PR creator have carefully read & adher to the guidelines of the project.
- [X] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, @kumarjeetray, great job!
But before merging this, could you please consider removing the alphabets you used in the readme to list since bullet points already exist.

**Comment by kumarjeetray** [comment]
> 
> 
> Hey, @kumarjeetray, great job!
> But before merging this, could you please consider removing the alphabets you used in the readme to list since bullet points already exist.

Sure. Give me a minute please

**Comment by GowthamGoush** [comment]
You may refer to #145 for the standard readme template.

**Comment by kumarjeetray** [comment]
> 
> 
> > Hey, @kumarjeetray, great job!
> > But before merging this, could you please consider removing the alphabets you used in the readme to list since bullet points already exist.
> 
> Sure. Give me a minute please

Done

**Comment by kumarjeetray** [comment]
> 
> 
> You may refer to #145 for the standard readme template.

Yeah I have done it that way only but since no third party libraries were used I ommited that part.

**Comment by RaveenaBhasin** [comment]
@kumarjeetray If there are no third-party libraries used in the script consider writing No third-party libraries under that heading.

**Comment by kumarjeetray** [comment]
> 
> 
> @kumarjeetray If there are no third-party libraries used in the script consider writing No third-party libraries under that heading.

Okay

**Comment by kumarjeetray** [comment]
> 
> 
> @kumarjeetray If there are no third-party libraries used in the script consider writing No third-party libraries under that heading.

Done. Please do check

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
