### PR TITLE
Automate Screenshot function using Python

### LINKED ISSUE #650: Automate Screenshot function using python
**Is your feature request related to a problem? Please describe.**
By this method we can automate screen shot function and can customize it based on our preferences.

**Describe the solution you'd like**
This uses pyautogui module to implement this function

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by PradeepBaipadithaya**
Fixes #650 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by RaveenaBhasin** [comment]
@PradeepBaipadithaya Kindly mention related issue.

**Comment by PradeepBaipadithaya** [comment]
@RaveenaBhasin  I didnt get were to mention issue.
I have created  4 new issue.

**Comment by PradeepBaipadithaya** [comment]
Is this project has successfully merged???
I am new to LGM - SOC.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please consider adding the images to the readme properly.

**Comment by GowthamGoush** [comment]
> @RaveenaBhasin I didnt get were to mention issue.
> I have created 4 new issue.



> Is this project has successfully merged???
> I am new to LGM - SOC.

Alright, no worries, @PradeepBaipadithaya.

All you have to do is:
     - Fix the images in the readme
     - Mention the issue number which you are working on. You may refer to this #590, to get a fair idea of a successful pull request.

**Comment by PradeepBaipadithaya** [comment]
I have uploaded Automate_Screenshot folder again.
Please review it sir/mam.
I have corrected my readme.md as per issue #590 .

**Comment by GowthamGoush** [comment]
> One last step, mention the issue number so that we could merge.

Mention the issue number above the checklist and next to the keyword "Fixes".

**Comment by PradeepBaipadithaya** [comment]
I have updated issue #683

**Comment by GowthamGoush** [comment]
> I have updated issue #683

This number refers to this pull request. You have to refer to the issue for which you have written this script.

**Comment by PradeepBaipadithaya** [comment]
I have updated issue number by #650

**Comment by GowthamGoush** [comment]
> I have updated issue number by #650

Alright, great job, @PradeepBaipadithaya.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
