### PR TITLE
Implemented the auto complete feature in Dictionary in Python

### LINKED ISSUE #531: Add auto complete feature in Dictionary in python
In the project that is in python folder named "Dictionary in Python",
want to add autocomplete feature while using entry in label,
like when we write some letter, then we get suggestion of list of words beginnin with that prefix in drop down list, and then if our word we want to enter appears there in drop down list , then we can directly select from there.

And also want to add Exit button in dictionary

And a exit dialog box asking permission of user to make sure if he/she wants to exit.

it will look like this,

### PR DESCRIPTION
**Pull request by akash435**
Fixes #531

## Changes done 

Updated the gui window of dictionary.
Added clear and exit button also.
Inplemented the auto complete feature  in the entry label, using csv data file(as dataset).
Also implemented the exit dialog box to appear whenever we try to  exit.
Added words.csv file which i used in implementing autocomplete feature.

## Checklist

- [x] The PR title starts with "Fix #531".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by akash435** [comment]
@Tejas1510 @GowthamGoush @RaveenaBhasin , created a pr related to adding auto complete feature in Dictionary in python, please check it.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly add more to the readme as per #145 and adjust the image size if possible.

**Comment by akash435** [comment]
@GowthamGoush , updated the readme as per readme format, please check it.

**Comment by akash435** [comment]
@GowthamGoush @RaveenaBhasin @Tejas1510 , please check i have updated the readme as asked

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
