### PR TITLE
Reddit Video Downloader

### LINKED ISSUE #903: Reddit Video Downloader
**Is your feature request related to a problem? Please describe.**
I want to make a python script in which user has to give post URL which has video attached and the script will return post title, subreddit, author name and the video as a mp4 file. 

**Describe the solution you'd like**
I will use python to scrape data from the post and extract video and convert it into mp4 file so that user can watch it.

### PR DESCRIPTION
**Pull request by Akash20x**
## Explanation
This is a python script which will download the video of the post in reddit by asking user url of page of the post and also display post title, subreddit and author name. The video is stored in our local system as download.mp4

Fixes #903 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

output

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, nice job, but before merging, please mention the "Libraries used" in the readme.

**Comment by Akash20x** [comment]
> Hey, nice job, but before merging, please mention the "Libraries used" in the readme.

OK

**Comment by Akash20x** [comment]
@GowthamGoush I have done the required changes, please merge my pull request

**Comment by GowthamGoush** [comment]
I believe it is enough to mention the library alone and version number isn't necessary.

**Comment by Akash20x** [comment]
> I believe it is enough to mention the library alone and version number isn't necessary.

I changed it, Check now

**Review by GowthamGoush — APPROVED** [review]

**Pull request merged**
