### PR TITLE
Imporved Website Blocker

### LINKED ISSUE #338: Improve Python Website Blocker
**Is your feature request related to a problem? Please describe.**
Make the python Website blocker more robust by adding a UI and some real web-filtering to it.
Also imporve its readme.

**Describe the solution you'd like**
Will be using Tkinter or Python-eel for the UI

~~**Describe alternatives you've considered**~~
~~A clear and concise description of any alternative solutions or features you've considered.~~
This issue is a part of my contribution in LGM-SOC'21
Please Assign @Tejas1510

### PR DESCRIPTION
**Pull request by Rutuj-Runwal**
Fixes #338 

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by GowthamGoush** [comment]
@Rutuj-Runwal excellent job, but could you please update the readme as well?

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Readme has to be updated.

**Comment by Rutuj-Runwal** [comment]
Changes updated @GowthamGoush

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Since you have made changes to the UI, the images in the readme file have to be updated. Just add the latest images to the readme.

**Comment by Tejas1510** [comment]
@Rutuj-Runwal Awesome work bro
Merging the PR

**Pull request merged**
