### PR TITLE
HangMan Game in C++

### LINKED ISSUE #575: Hangman Game in C++
i want to work on this issue

### PR DESCRIPTION
**Pull request by agamgupta2015**
## Explanation

  
Fixes #575 

## Checklist

- [x] The PR title starts with "Fix #575  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by agamgupta2015** [comment]
Please review

**Comment by RaveenaBhasin** [comment]
@agamgupta2015 Update readme acc. to #145

**Comment by amanjha8100** [comment]
@agamgupta2015 please do look into what Raveena has pointed out to?

**Comment by mehabhalodiya** [comment]
@agamgupta2015 any updates?

**Comment by GowthamGoush** [comment]
Since there is no response yet, I'm closing this issue.

**Pull request closed without merging**
