### PR TITLE
Fix #867

### LINKED ISSUE #867: Relaxer App using Vanilla JavaScript
**Is your feature request related to a problem? Please describe.**
A relaxing breathing app with a visual director to tell you when to breathe in, hold and breathe out

**Describe the solution you'd like**
To be built using HTML, CSS, and JavaScript. 
- Create circle and gradient circle with CSS
- Create and animate pointer (Small circle)
- Create grow and shrink animations
- Add JavaScript to create the breath animation effect

Kindly assign me this issue, Thank you in advance :)

### PR DESCRIPTION
**Pull request by nagasaisriya**
## Explanation

  
Fixes: #867 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, great job but one last step, kindly consider ordering the contents of readme as per #145.

**Comment by nagasaisriya** [comment]
> Hey, great job but one last step, kindly consider ordering the contents of readme as per #145.

Hey, sure. But there's no such input or output image, so what should I place instead? Actually, I've gone through few merged prs under JavaScript and they had the same format, so I did in that way.

**Comment by nagasaisriya** [comment]
Hey @GowthamGoush , I've modified the readme according to #145 . Do check it out and tell if anymore changes needed to be done. Thank you :)

**Comment by GowthamGoush** [comment]
Hey, apologies for the delay. Your changes are perfect and ready to get merged.

**Review by GowthamGoush — APPROVED** [review]

**Comment by nagasaisriya** [comment]
> Hey, apologies for the delay. Your changes are perfect and ready to get merged.

No problem at all! Thanks a lot @GowthamGoush 👍

**Pull request merged**
