### PR TITLE
Pokedex

### PR DESCRIPTION
**Pull request by Ayush7614**
Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### CODE REVIEW

**Comment by Ayush7614** [comment]
This is pull for #194 issue plss @Tejas1510 sir plss review it and thanku for saying me to stash all you commits in one commits this will help me to learn git commands for making a pull request from git beacuse i added a code manually one one file thats why commits are so many

**Comment by Tejas1510** [comment]
@Ayush7614 The Readme is lagging the images

**Comment by Ayush7614** [comment]
so okk i added the imaages

**Comment by Ayush7614** [comment]
@Tejas1510 sir now plss review it i have added the images and screenshots link for output

**Comment by Tejas1510** [comment]
@Ayush7614 The images are still now shown 
Convert them to jpg and add
You will not get points unless you do this even if the PR is merged

image

**Pull request merged**
