### PR TITLE
Automatic youtube video downloader.

### PR DESCRIPTION
**Pull request by spursbyte**
This is my approach for the youtube downloader made with tinkter  and python.I have also attached a screenshot for the same.kindly review it.

### CODE REVIEW

**Comment by Tejas1510** [comment]
Add a readme file with proper explanation of the app and screenshot of input and output

**Comment by spursbyte** [comment]
> Add a readme file with proper explanation of the app and screenshot of input and output

Ok on it

**Comment by Tejas1510** [comment]
Good Work @spursbyte

**Comment by spursbyte** [comment]
> Good Work @spursbyte

THANKS SO WILL I UPDATE THE EXCEL SHEET NEXT??

**Pull request merged**
