### PR TITLE
Fix #506 Added Space Invaders Game in python

### LINKED ISSUE #506: Space Invaders Game in Python
### I'm submitting a 
- [x] feature request.

### Do you want to work on this issue?
 yes
Please assign this issue labels. I want to contribute in this amazing project under LGMSOC21.

### Describe the feature?
This is a space invaders game build using Pygame library of python. In this game user can fight the monsters with bullet and also their score get displayed.

### PR DESCRIPTION
**Pull request by Kritika-2000**
## Explanation
Uploaded the Space Invaders Game in Python

  
Fixes #506:

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, @Kritika-2000, great job! 
Before merging this, consider removing files that are unnecessary for this script to execute.

**Comment by Kritika-2000** [comment]
> Hey, @Kritika-2000, great job!
> Before merging this, consider removing files that are unnecessary for this script to execute.

Thank you sir ! ok I will remove some files

**Review by Kritika-2000 — COMMENTED** [review]
Removed extra files

**Comment by RaveenaBhasin** [comment]
@Kritika-2000 The source code for the game is copied directly from https://github.com/attreyabhatt/Space-Invaders-Pygame
that too without any changes.
We appreciate it if you kindly write scripts on your own as in this way you will be unable to learn anything while contributing.
Thanks for your valuable time, hoping to have the next script from you with less than 60-70% plagiarism.

**Pull request closed without merging**
