### PR TITLE
Typing Speed Test

### LINKED ISSUE #307: Typing Speed Test
**Is your feature request related to a problem? Please describe.**
It will be a project which will test the typing speed, show the accuracy, speed and wpm as output

**Describe the solution you'd like**
The user has to type a given sentence based on which all the outputs will be shown

**Additional context**
I can do this in Python as well as Javascript

### PR DESCRIPTION
**Pull request by Debashish-hub**
Fixes #307

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:

Typing speed test in python

### Snapshot:

Snapshot is in readme

### CODE REVIEW

**Comment by amanjha8100** [comment]
Debashish fix the typo fro pyjokes in readme!

**Comment by Debashish-hub** [comment]
> Debashish fix the typo for pyjokes in readme!

Sorry, I didn't get it

**Comment by amanjha8100** [comment]
You have made a minute typing error in readme file, it will be "pyjokes" rather than "pjokes". Documentation is really important therefore just add a commit to this PR.

**Comment by Debashish-hub** [comment]
Sorry for that

**Pull request merged**
