### PR TITLE
Fix #554 Flappy bird game using js

### LINKED ISSUE #554: Flappy bird game using js
**Is your feature request related to a problem? Please describe.**
I want to add a Flappy Bird game in the js section of this project.

**Describe the solution you'd like**
A game built using html css Bootstrap and js which will add value to this repo.

### PR DESCRIPTION
**Pull request by Saup21**
## Flappy bird game added to js folder.

  
Fixes #554 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by Saup21** [comment]
Don't merge it I have accidentally sent another PR on this branch for a different issue.

**Comment by GowthamGoush** [comment]
So, shall I close this PR?

**Comment by Saup21** [comment]
How about I delete the code that was meant for some other issue from this branch?

**Comment by Saup21** [comment]
I'm closing the PR since it will cause unnecessary merge conflicts at this point @GowthamGoush

**Pull request closed without merging**
