### PR TITLE
Added Shutdown your pc by voice command

### LINKED ISSUE #651: Shutdown computer using voice command.
**Is your feature request related to a problem? Please describe.**
This method can automate your work of shut downing your computer.

**Describe the solution you'd like**
This method is combination of os module + Speech recognition + win32.client module which can automate this method.

### PR DESCRIPTION
**Pull request by PradeepBaipadithaya**
## Explanation

  
Fixes #651 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by PradeepBaipadithaya** [comment]
I have uploaded issue #651 
please review it sir/mam.
Thank you so much @GowthamGoush  sir for guiding me in each step in my previous pull request.

**Comment by RaveenaBhasin** [comment]
@PradeepBaipadithaya Kindly add required images in the readme.

**Comment by PradeepBaipadithaya** [comment]
Sorry i dont have any picture for this project.

**Comment by PradeepBaipadithaya** [comment]
*images

**Comment by GowthamGoush** [comment]
> I have uploaded issue #651
> please review it sir/mam.
> Thank you so much @GowthamGoush sir for guiding me in each step in my previous pull request.

Hey, thanks, man! Feel free to call us by our name. We are just students.

If possible, could you take a snap of the script while running before you deliver the voice command to shutdown?

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Also, please make sure to remove the changes made on irrelevant files.

**Comment by PradeepBaipadithaya** [comment]
I have updated read me .
please review it .

**Comment by PradeepBaipadithaya** [comment]
i had committed 2 of my issue with a gap of 10 min, but here it is showing that i have committed and i cannot mention the issue no to that. Will it cause any error.
Is there any rule that only after merging one issue completely, then we can pull request for another issue.

**Comment by GowthamGoush** [comment]
> i had committed 2 of my issue with a gap of 10 min, but here it is showing that i have committed and i cannot mention the issue no to that. Will it cause any error.
> Is there any rule that only after merging one issue completely, then we can pull a request for another issue.

Regarding the pull request, you may raise as many as you want for different issues, but it must be done by creating a separate branch. So, basically, you've to create a new branch for a new issue, and that is one of the best practices that you could follow.

**Comment by PradeepBaipadithaya** [comment]
Ok

**Comment by PradeepBaipadithaya** [comment]
Why 
codeQL / Analyze (cpp) (pull_request) Failing after 54s — Analyze (cpp)
CodeQL / Analyze (java) (pull_request) Failing after 34s — Analyze (java)
are failing.
what is the reason for that.

**Comment by PradeepBaipadithaya** [comment]
Since i have included 2 issue in same pull request, should i close this pull request and make a new pull request.

**Comment by GowthamGoush** [comment]
> Why
> codeQL / Analyze (cpp) (pull_request) Failing after 54s — Analyze (cpp)
> CodeQL / Analyze (java) (pull_request) Failing after 34s — Analyze (java)
> are failing.
> what is the reason for that.

If you are curious about that, you may refer to [this](https://github.com/features/actions) site.

**Comment by GowthamGoush** [comment]
> Since i have included 2 issue in same pull request, should i close this pull request and make a new pull request.

Actually, you have to revert the changes and raise a pr from a different branch.

**Pull request closed without merging**
