### PR TITLE
added a Guessing Game  in C programmimg

### PR DESCRIPTION
**Pull request by rishabhrathore055**
#330

Fixes #

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### Description:

added a Guessing Game Using C programming  which generate random Number Between 1 to 100

### CODE REVIEW

**Comment by GowthamGoush** [comment]
@rishabhrathore055, there is a typo in the readme file because of which the output image is not displayed. Much appreciated if you fix it.

**Comment by rishabhrathore055** [comment]
@GowthamGoush Yup i fixed this

**Comment by GowthamGoush** [comment]
> @GowthamGoush Yup i fixed this

Good job, but the issue was with the name of the image mentioned in the readme. However, I've fixed it.

**Comment by rishabhrathore055** [comment]
ThankYou!!

**Pull request merged**
