### PR TITLE
Currency Converter

### LINKED ISSUE #559: Currency Converter in Python
**Is your feature request related to a problem? Please describe.**
When we need to convert currency every time we need to google it but instead of that what if we our script do that.

**Describe the solution you'd like**
I would like to write a python script in which we can convert currency by just making a dictionary of currency as another file in same folder (getting currency rates from google for dictionary).

### PR DESCRIPTION
**Pull request by neelshah2409**
## Explanation:
Here we can covert INR into various currencies using the data of rates from google ,we will make currency file in which all the rates will be there and then in the script we will read and fetch from that file and then convert it into any currency.
We firstly need to get the rates from google and copy it into currency file then we need to run the script and then mention the currency in which we need to convert.

  
Fixes: #559 

## Checklist

- [x] The PR title starts with "Fix #559 ".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

## Output:
output_1(currency)
output_2(currency)

### CODE REVIEW

**Comment by neelshah2409** [comment]
Please review my PR .

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
The "Third-Party Libraries Required" section of the readme is empty. Kindly consider adding "No library used" under this section.

**Comment by neelshah2409** [comment]
@GowthamGoush Sir I had changed the readme and please review it and also see the #595 and please assign me.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please follow the hierarchy level of the headings. Increase the size of the heading for "Third-Party Libraries Required".

**Comment by neelshah2409** [comment]
@GowthamGoush Sir done and sorry for that .

**Comment by neelshah2409** [comment]
@GowthamGoush Sir Please review this PR.

**Pull request merged**
