### PR TITLE
Add a Tic Tac Toe Game with better UI 

### PR DESCRIPTION
**Pull request by Atif0604**
## Explanation

  - Changed the UI Of the game as well as the working script
  - Add a Tic Tac Toe Game with better UI #644
  - No 3rd party library used

Fixes: #644 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by Atif0604** [comment]
Hey @RaveenaBhasin 
Please Review my PR

**Comment by RaveenaBhasin** [comment]
@Atif0604 Kindly mark all the check boxes properly and mention the third-party library used in the script. If not used then consider writing no third party libraries used.

**Comment by Atif0604** [comment]
> @Atif0604 Kindly mark all the check boxes properly and mention the third-party library used in the script. If not used then consider writing no third party libraries used.

Done

**Comment by Atif0604** [comment]
hey @RaveenaBhasin  can you please review my PR

**Comment by RaveenaBhasin** [comment]
> > @Atif0604 Kindly mark all the check boxes properly and mention the third-party library used in the script. If not used then consider writing no third party libraries used.
> 
> Done @RaveenaBhasin

Where have you done the changes?

**Comment by Atif0604** [comment]
> > > @Atif0604 Kindly mark all the check boxes properly and mention the third-party library used in the script. If not used then consider writing no third party libraries used.
> > 
> > 
> > Done @RaveenaBhasin
> 
> Where have you done the changes?

I have written no third party libraries used and all check boxes were marked correctly

**Comment by Atif0604** [comment]
> > > @Atif0604 Kindly mark all the check boxes properly and mention the third-party library used in the script. If not used then consider writing no third party libraries used.
> > 
> > 
> > Done @RaveenaBhasin
> 
> Where have you done the changes?

Can you exactly specify where do you want the changes either in files or PR description @RaveenaBhasin

**Comment by RaveenaBhasin** [comment]
> > > > @Atif0604 Kindly mark all the check boxes properly and mention the third-party library used in the script. If not used then consider writing no third party libraries used.
> > > 
> > > 
> > > Done @RaveenaBhasin
> > 
> > 
> > Where have you done the changes?
> 
> Can you exactly specify where do you want the changes either in files or PR description @RaveenaBhasin

You have to make changes in the Readme file and mark the check boxes in the PR description. For checking the boxes in the PR description you have to simply write x within the square brackets without any space.

**Comment by Atif0604** [comment]
Is It Ok now ? @RaveenaBhasin

**Comment by Atif0604** [comment]
Hey @RaveenaBhasin is there anything else to change?

**Review by mehabhalodiya — APPROVED** [review]

**Comment by mehabhalodiya** [comment]
@RaveenaBhasin Have a look at this!

**Comment by Atif0604** [comment]
hey @RaveenaBhasin @mehabhalodiya when will be my pr is going to merge it has been around 18 days since i made the changes asked

**Comment by Atif0604** [comment]
Hey @GowthamGoush Could please have look into this

**Pull request merged**
