### PR TITLE
Adding verify_email.py

### LINKED ISSUE #469: can i add script to verify the email-address?
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by richabh456**
## Explanation

  
Fixes #:469

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.
fixes #469

### CODE REVIEW

**Comment by richabh456** [comment]
please review my pr.

**Comment by richabh456** [comment]
fixes #469

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly add the readme as per #145.

**Comment by richabh456** [comment]
@GowthamGoush sir i have added readme file ,please verify it.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please consider adding few images of your script in the readme.

**Comment by GowthamGoush** [comment]
@richabh456, any progress?

**Comment by GowthamGoush** [comment]
Since there is no response or any progress, I'm unassigning the issue and closing PR.

**Pull request closed without merging**
