### PR TITLE
Added Automate_Screenshot code inside Automate_Screenshot folder insi…

### PR DESCRIPTION
**Pull request by PradeepBaipadithaya**
I have uploaded a Automate_Screenshot.py code inside my Automate_Screenshot folder in python folder.
Please review it, sir.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly add a readme as per #145.

**Comment by GowthamGoush** [comment]
Also, please do not remove anything in the template while raising a pull request.

**Comment by PradeepBaipadithaya** [comment]
Ok sir.

**Comment by PradeepBaipadithaya** [comment]
I have updated readme.md file.
Please review it sir.

**Pull request closed without merging**
