### PR TITLE
Added Latitude-Longitude Pair Verifier in Python Scripts

### LINKED ISSUE #980: Latitude-Longitude Pair Verifier
Language : Python

In this script, will create an application using tkinter GUI,

using this application user will be able to verify the pair of latitude and longitude.

First will allow user to enter the longitude and latitude and the will tell whether that pair is valid or not.

And if valid will show user about location which is around that latitude and longitude.

### PR DESCRIPTION
**Pull request by akash435**
- A "Latitude - Longitude Pair Verifier" is an application created in python with tkinter gui.
- In this application, user can enter any latitude and longitude and verify whether that latitude and longitude pair is valid or not.
- Also if the pair is valid then user can also locate that latitude and longitude on the earth and see which country is around that latitude and longitude along with country code.
- Also is the pair is not valid, then error message will be shown for the same and that latitude and longitude cannot be located using locate button.
- for locating, used the world_location.csv data, and read using pandas library.
  
Fixes #980

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
Feature:
In this script, can you add vice versa?

Like if the user enters the country name, then the pair of longitude and latitude is displayed.

**Comment by akash435** [comment]
@mehabhalodiya i have already done that in previous script #709, so i haven't added the vice versa in it.

**Review by GowthamGoush — COMMENTED** [review]
Please consider removing unnecessary comments.

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya i have already done that in previous issue #709, so i haven't added the vice versa in it. If you want me to add in this also then i can update it.

You can perform this both features in one GUI by initially giving two options, whichever user wants to choose?

**Comment by akash435** [comment]
> Please consider removing unnecessary comments.

@GowthamGoush  Done the changes

**Comment by akash435** [comment]
> > @mehabhalodiya i have already done that in previous issue #709, so i haven't added the vice versa in it. If you want me to add in this also then i can update it.
> 
> You can perform this both features in one GUI by initially giving two options, whichever user wants to choose?

@mehabhalodiya should i update like this?

**Comment by mehabhalodiya** [comment]
> > @mehabhalodiya i have already done that in previous issue #709, so i haven't added the vice versa in it. If you want me to add in this also then i can update it.
> 
> You can perform this both features in one GUI by initially giving two options, whichever user wants to choose?

Or else if you don't want to do this then I have one other feature to add:
we can find the “Distance” between a member location and the coordinates displayed.

**Comment by mehabhalodiya** [comment]
> > > @mehabhalodiya i have already done that in previous issue #709, so i haven't added the vice versa in it. If you want me to add in this also then i can update it.
> > 
> > 
> > You can perform this both features in one GUI by initially giving two options, whichever user wants to choose?
> 
> Or else if you don't want to do this then I have one other feature to add:
> we can find the “Distance” between a member location and the coordinates displayed.

@RaveenaBhasin @GowthamGoush what you say?

**Comment by akash435** [comment]
> > > @mehabhalodiya i have already done that in previous issue #709, so i haven't added the vice versa in it. If you want me to add in this also then i can update it.
> > 
> > 
> > You can perform this both features in one GUI by initially giving two options, whichever user wants to choose?
> 
> Or else if you don't want to do this then I have one other feature to add:
> we can find the “Distance” between a member location and the coordinates displayed.

@mehabhalodiya means distance between our's current location and co-ordinates displayed. is it?

**Comment by mehabhalodiya** [comment]
> > > > @mehabhalodiya i have already done that in previous issue #709, so i haven't added the vice versa in it. If you want me to add in this also then i can update it.
> > > 
> > > 
> > > You can perform this both features in one GUI by initially giving two options, whichever user wants to choose?
> > 
> > 
> > Or else if you don't want to do this then I have one other feature to add:
> > we can find the “Distance” between a member location and the coordinates displayed.
> 
> @mehabhalodiya means distance between our's current location and co-ordinates displayed. is it?

Yes exactly!
If you are doing so then I will increase the level of PR.

**Comment by akash435** [comment]
> > > > > @mehabhalodiya i have already done that in previous issue #709, so i haven't added the vice versa in it. If you want me to add in this also then i can update it.
> > > > 
> > > > 
> > > > You can perform this both features in one GUI by initially giving two options, whichever user wants to choose?
> > > 
> > > 
> > > Or else if you don't want to do this then I have one other feature to add:
> > > we can find the “Distance” between a member location and the coordinates displayed.
> > 
> > 
> > @mehabhalodiya means distance between our's current location and co-ordinates displayed. is it?
> 
> Yes exactly!
> If you are doing so then I will increase the level of PR.

@mehabhalodiya so please don't merge it now, i will add distance feature also then go for merging.

**Comment by akash435** [comment]
@mehabhalodiya , updated with the distance feature please check it.

**Comment by akash435** [comment]
please review my PR, there is no changes requested.

**Review by mehabhalodiya — APPROVED** [review]

**Comment by akash435** [comment]
please merge it as it is approved.

**Pull request merged**
