### PR TITLE
Matchmaker Game

### LINKED ISSUE #475: Matchmaker Game
**Is your feature request related to a problem? Please describe.**
When we were small kids we all have played card game in which all the cards are hidden then we have to get two same card and make a pair ,so why don't we can make it with python.

**Describe the solution you'd like**
I would like to write a python script using tkinter ,random ,time library and then make this game. It  will also have GUI.

### PR DESCRIPTION
**Pull request by neelshah2409**
Title: Matchmaker Game

Description: Here we had made a game in which all cards are hidden if we can find 2 cards having same symbol then only the cards will unhide. For this game we will use random ,tkinter,time library. This game is about memory firstly we have to draw a random card and then search for that card from another if we found then we have to search for another pair and we have to continue till last pair and then finally ends when we get all the pairs
  
Fixes #475 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x]  The PR creator have carefully read &  adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by neelshah2409** [comment]
Please review my PR.

**Comment by neelshah2409** [comment]
@RaveenaBhasin @GowthamGoush  please review my PR.

**Review by GowthamGoush — COMMENTED** [review]
Hey, that was a great job, but it would be nice to adjust the size of the images and fonts if possible.

**Comment by neelshah2409** [comment]
sir the the size of the symbols are by default , so sir it is fine? And any other changes.

**Comment by neelshah2409** [comment]
Please see further process of my PR @GowthamGoush @RaveenaBhasin

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@neelshah2409, you may refer to #145 and set the title text size accordingly.

**Comment by neelshah2409** [comment]
> @neelshah2409, you may refer to #145 and set the title text size accordingly.

Sir I had done and sir I am new to open source so formatting on git is of course new to me I had made changes up to my capabilities  if it is done then kindly approve my PR.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
