### PR TITLE
Fix #693 snake-game

### LINKED ISSUE #693: Snake Game built in ReactJs
**Describe the solution you'd like**
A snake game built in ReactJs.

Please assign this issue to me under LGMSoC'21

### PR DESCRIPTION
**Pull request by okarin1511**
Fixes #693 

## Explanation
A snake game built entirely in ReactJs

  
Fixes #: #693  

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Comment by RaveenaBhasin** [comment]
@okarin1511 Update the readme acc. to #145

**Comment by okarin1511** [comment]
Hi, @RaveenaBhasin I've made the required changes. Please take a look and let me know if any more changes are required.

**Comment by RaveenaBhasin** [comment]
@okarin1511 You have to make a Readme file for your script according to #145. I think you have made the changes in Hacking Scripts original Script which is not needed.

**Comment by mehabhalodiya** [comment]
@okarin1511 any updates?

**Pull request closed without merging**
