### PR TITLE
Dark & Light Mode added to existing Analog Clock

### LINKED ISSUE #528: Theme Clock using JS with dark and light mode
This is a Theme clock built using javascript. It also includes the feature of dark and light modes. 
It also shows the day & date.

@RaveenaBhasin @GowthamGoush Please Assign me under LGMSOC21.

### PR DESCRIPTION
**Pull request by ArshWalker**
## Explanation

  I have added the Dark&Light Mode toggle button in the existing Analog Clock Script. It's changing background to dark and 
  light color.
Fixes #528 :
 
Please review it...
## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Hey, @ArshWalker, could you please consider adding some snaps of these enhancements to the readme.

**Comment by RaveenaBhasin** [comment]
@ArshWalker Are u still working on this issue?

**Comment by ArshWalker** [comment]
@RaveenaBhasin Yes, I will do it by today.

**Comment by amanjha8100** [comment]
Hey, @ArshWalker what is the update?

**Pull request closed without merging**
