### PR TITLE
#339 React Todo list

### LINKED ISSUE #339: Imporve UI of ReactJS-TodoList
Please Assign @Tejas1510

### PR DESCRIPTION
**Pull request by Rutuj-Runwal**
## Explanation
- Enhanced the ReactJs Todo List
- Improved UI and responsiveness
- Added Dark Mode switch
- Added new icons
-  Added a feature to save todo list data in localstorage. [So even if you reload the browser the data stays]
  
Fixes #339 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please add the changes to the concerned readme file for this script.

**Comment by Rutuj-Runwal** [comment]
> Please add the changes to the concerned readme file for this script.

Added @GowthamGoush

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please add the latest images of this script and consider removing the changes you have made in the readme of Hacking Script. 

Important note: I don't really appreciate adding your profile to the readme as you have just added some enhancement to the existing one. Maybe consider adding it along with the previous contributor.

**Comment by Rutuj-Runwal** [comment]
> Please add the latest images of this script and consider removing the changes you have made in the readme of Hacking Script.
> 
> Important note: I don't really appreciate adding your profile to the readme as you have just added some enhancement to the existing one. Maybe consider adding it along with the previous contributor.

The images that I added are latest only...
I will remove the changes in the hacking-script readme IDK how it happened maybe cause there are 2 readmes in this project.Also will remove the profile link
Thanks

**Comment by GowthamGoush** [comment]
> > Please add the latest images of this script and consider removing the changes you have made in the readme of Hacking Script.
> > Important note: I don't really appreciate adding your profile to the readme as you have just added some enhancement to the existing one. Maybe consider adding it along with the previous contributor.
> 
> The images that I added are latest only...
> I will remove the changes in the hacking-script readme IDK how it happened maybe cause there are 2 readmes in this project.Also will remove the profile link
> Thanks

Actually, I don't have any issue when you add your profile if you have made the entire script, but here, since it was an enhancement, I've requested you.

**Comment by GowthamGoush** [comment]
@Rutuj-Runwal, any progress?

**Comment by GowthamGoush** [comment]
Since there is no response or any progress, I'm unassigning the issue and closing PR.

**Pull request closed without merging**
