### PR TITLE
Text Translator in Python

### PR DESCRIPTION
**Pull request by djm-1**
Fixes https://github.com/Tejas1510/Hacking-Scripts/issues/171

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:

It reads the contents of a .txt file and translates the text into regional languages and stores the output in .txt format
### Change logs:

* Can translate contents of a text document.

* Translated version is stored in output text file.

#### Input file
Screenshot (26)
#### Output file
Screenshot (27)

### CODE REVIEW

**Comment by Tejas1510** [comment]
@djm-1 The Readme File Should be in the format provided along with input and output images

**Comment by djm-1** [comment]
Sir I have modified it now.

**Comment by Tejas1510** [comment]
Great Work @djm-1

**Comment by djm-1** [comment]
Thank you Sir... please assign it labels for Jwoc and level

**Pull request merged**
