### PR TITLE
Fix #327 Added a memory game in JavaScript

### LINKED ISSUE #327: Wants to add a memory game in javascript projects
@Tejas1510  please assign me this task under Lgmsoc'21

### PR DESCRIPTION
**Pull request by Kartikey0205**
## Explanation
* `Adding a game named Memory Game which is made in JavaScript , HTML , CSS `
* `It was most addicted game !!` 

  
Fixes #327 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

@GowthamGoush @amanjha8100  please review it and merge it .

# If you want to see how this game looks then click below and play it and enjoy (if you finds it good please level it under Lgm-soc'21)
[Memory Game](https://kartikey0205.github.io/Hacking-Scripts/Javascript/memoryGame/index.html)

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Does not follow the guidelines.

**Comment by Kartikey0205** [comment]
No @GowthamGoush  , it was my work on Frontend Bootcamp from learnOnline.com

there I learn another memory game and here I had tried a new version of it , you may check my twitter as for that certification and memory game as well

[Twitter uploads](https://twitter.com/KartikeyDubey02/status/1399438691337072640/photo/1) 
[Certification code](https://twitter.com/KartikeyDubey02/status/1399009748586962945)

**Comment by Kartikey0205** [comment]
@GowthamGoush please check and let me know ! please

**Comment by Kartikey0205** [comment]
> @Kartikey0205, it seems like you have copied the code from the resources available online. The motive of this open-source program is to provide the opportunity to learn how to contribute to open-source and learn something new.
> Copy/Pasting the code is not constructive, so kindly avoid such plagiarism, and I'm closing this issue.

PLease check

**Comment by Kartikey0205** [comment]
@GowthamGoush  if you wish I can just make a PR on what I had learned and made in my bootcamp in whixh I had used particle.js typed.js

**Pull request closed without merging**
