### PR TITLE
Ping-Pong Game

### LINKED ISSUE #402: Ping Pong Game using JS
**Is your feature request related to a problem? Please describe.**
Ping Pong Game is a web app built using JS.

In this, you can control your side using a stick while playing against computer. And your score is managed.

@Tejas1510 Please assign me this issue.

### PR DESCRIPTION
**Pull request by ArshWalker**
Ping-Pong Game (issue assigned to me!)

Fixes #402 

### Checklist:
- [x] My branch is up-to-date with upstream/master branch.

### Description:

This PR is about creating a Ping-Pong Game using JS.
Play a game against Computer.
### Change logs:

Added Ping-Pong Game.

### Snapshot:

Pingpong

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Could you please update the readme with images as per #145?

**Comment by ArshWalker** [comment]
> Could you please update the readme with images as per #145?

**Comment by ArshWalker** [comment]
Please review it, I have made the changes.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by GowthamGoush** [comment]
Good job, @ArshWalker.

**Pull request merged**
