### PR TITLE
Added code for Scientific Calculator using Python and Tkinter

### LINKED ISSUE #592: Scientific Calculator using Tkinter and Python
**Describe the solution you'd like**
Building a scientific calculator using Python programming language and Tkinter for rich GUI design, to calculate and perform all scientific calculation operations. Includes operations from algebraic to trigonometric, logarithmic along with square root, factorial and exponential functions. Users can see numbers, operators, signs and keys which they should press or click in order to perform any specified task.

**Additional context**
Would like to work on this as a participant of LGM-SOC'21.

### PR DESCRIPTION
**Pull request by PriyankaHotchandani**
## Explanation

  
Built a scientific calculator along with a rich GUI design. It calculates and performs all scientific calculation operations ranging from algebraic to trigonometric, logarithmic along with square root, factorial, exponential and many more functions. Users can see numbers, operators, signs and keys which they should press or click in order to perform any specified task.

Fixes #592 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Hey, @PriyankaHotchandani, amazing work, and I really appreciate the enthusiasm you showed towards this project by adding changes to the readme, but I prefer to fix those in a separate issue.
So please consider removing the changes in the readme in this PR. You may raise a new issue to fix them all.

**Comment by PriyankaHotchandani** [comment]
@GowthamGoush Should I create a new pull request for this existing issue (#592) by discarding the readme changes?

**Comment by GowthamGoush** [comment]
Not really required. Just consider removing the changes that you have made for the readme.

**Comment by PriyankaHotchandani** [comment]
Done, removed the changes in readme file.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Pull request merged**
