### PR TITLE
React js joke app added

### LINKED ISSUE #690: Joke-Generator in ReactJS
**Is your feature request related to a problem? Please describe.**
No, this is an enhancement. I was thinking about adding a lame joke generator as another project in ReactJS projects.
I would integrate an API request and generate random cute jokes.

**It would look something like this**

image

**Additional context**
Please Assign me this issue under **LGMSOC21**

### PR DESCRIPTION
**Pull request by varshitha1707**
## Explanation

I added the React project Joke Generator

  
Fixes #690 

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please consider removing the changes added to the readme of the main repo and modify the readme of your script as per #145.

**Comment by varshitha1707** [comment]
> Please consider removing the changes added to the readme of the main repo and modify the readme of your script as per #145.

Yes, I have updated the Readme. Thank you for letting me know about #145 
Also, if there is any other change which is needed to be done, please let me know.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Please remove the changes from the main readme file.

**Comment by varshitha1707** [comment]
> Please remove the changes from the main readme file.

I'm really sorry but, I dont understand what I have to remove in the main readme 
The changed you requested are already changed.

Can you please elaborate on what I need to change?

**Review by GowthamGoush — APPROVED** [review]
Alright, great job, @varshitha1707. Ready to be merged.

**Pull request merged**
