### PR TITLE
Text File To PDF(Python)

### PR DESCRIPTION
**Pull request by neelshah2409**
## Explanation
Here we  had converted text file to pdf , so for that we will use fpdf library and firstly read the text file and then will make a pdf of it in the same folder , here the text size of pdf can be changed by us.
  
Fixes: #901

## Checklist

- [x] The PR title starts with "Fix #issue_number".  
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

## Output
Screenshot (656)

### CODE REVIEW

**Comment by neelshah2409** [comment]
@RaveenaBhasin @GowthamGoush @mehabhalodiya Please review my PR.

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
Kindly consider removing unnecessary files. Also, make sure to add the output image in this PR.

**Comment by neelshah2409** [comment]
> Kindly consider removing unnecessary files. Also, make sure to add the output image in this PR.

Sir here myfile.txt is the text file which we are converting to pdf and mypdf.pdf is the resultant output. So there are no extra files .

**Comment by neelshah2409** [comment]
@RaveenaBhasin @GowthamGoush
 Please see review this PR.

**Comment by GowthamGoush** [comment]
Then it means that your code is static and works only for that specific files. If possible, please consider making it dynamic by allowing the user to choose the file.

**Comment by neelshah2409** [comment]
Sir here user just need to have the text file in the same folder as of script 

> Then it means that your code is static and works only for that specific file. If possible, please consider making it dynamic by allowing the user to choose the file.

No sir it is dynamic only but you said previously that remove unnecessary files that's why I told about that file and this files are kept just for reference/proof . User can just need to have text file in the same folder as of script and then he/she can get pdf as output after running the script.

**Comment by neelshah2409** [comment]
@GowthamGoush Sir please see it.

**Comment by GowthamGoush** [comment]
> > Then it means that your code is static and works only for that specific file. If possible, please consider making it dynamic by allowing the user to choose the file.
> 
> No sir it is dynamic only but you said previously that remove unnecessary files that's why I told about that file and this files are kept just for reference/proof . User can just need to have text file in the same folder as of script and then he/she can get pdf as output after running the script.

No, I had a look and it's static since the user is not provided with the option to choose a file that he/she wishes to convert. Maybe try reformatting your code to include this feature.

**Comment by neelshah2409** [comment]
> > > Then it means that your code is static and works only for that specific file. If possible, please consider making it dynamic by allowing the user to choose the file.
> > 
> > 
> > No sir it is dynamic only but you said previously that remove unnecessary files that's why I told about that file and this files are kept just for reference/proof . User can just need to have text file in the same folder as of script and then he/she can get pdf as output after running the script.
> 
> No, I had a look and it's static since the user is not provided with the option to choose a file that he/she wishes to convert. Maybe try reformatting your code to include this feature.


Yes sir I tried to provide user a feature using os library for selecting the file but when other screen for selecting the file pops up then program crashes , so that is why I had given here dynamically. So sir if it is fine then please approve this PR.

**Comment by GowthamGoush** [comment]
Actually, the program should not crash if you've written a proper code.  Anyway, I'll merge this time but make sure to avoid this next time.

**Review by GowthamGoush — APPROVED** [review]

**Pull request merged**
