### PR TITLE
Added The Dodge The Ball Game in Python

### PR DESCRIPTION
**Pull request by Deep06-11**
Fixes: #800 

##Checklist

- [x]  The PR title starts with "Fix #issue_number".
- [x] My branch is up-to-date with the main branch.
- [x] The PR does not contain any unnecessary auto-generated code.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adher to the guidelines of the project.
- [x] The PR is raised after the issue has been assigned to the PR creator.

## Explanation
I have added Dodge the Ball Game in Python using the Tkinter library.
Please review it.

### CODE REVIEW

**Review by GowthamGoush — CHANGES_REQUESTED** [review]
@Deep06-11, Kindly consider adding back the checkboxes as in the pull request template in your initial comment of this pull request.

**Comment by Deep06-11** [comment]
> @Deep06-11, Kindly consider adding back the checkboxes as in the pull request template in your initial comment of this pull request.

@GowthamGoush Changes done.

**Review by GowthamGoush — COMMENTED** [review]
@Deep06-11, It seems like you've indulged in plagiarism. Remember, at the end of this program, the real takeaway is the things that you've learned across the 30 days and not the points/swags. So, kindly take advantage of this program and learn to the fullest possible.

**Comment by GowthamGoush** [comment]
I'm currently closing this PR.

**Pull request closed without merging**
