### PR TITLE
Face recognition using JavaScript #341

### LINKED ISSUE #341: Want to make a Face recognition Script using JavaScript under LGM-SOC'21
I want to make a script of Face recognition which every one can use and test in there browser without any additional install.
@Tejas1510 , Can you assign me this issue under LGM-SOC'21

### PR DESCRIPTION
**Pull request by Pradhuman-singh5**
Fixes #341

### Checklist:
- [ ] My branch is up-to-date with upstream/master branch.

### Description:

Face Recognition script added. Now you can use this in your browser.

### CODE REVIEW

**Comment by GowthamGoush** [comment]
Great efforts, @Pradhuman-singh5, but could you please take some moment in adding more to your readme? You may refer to the previous works of the participants if you wish to.

**Comment by Pradhuman-singh5** [comment]
@GowthamGoush  , Readme is updated . Take a Look at it again and tell me for any other suggestions.

**Comment by GowthamGoush** [comment]
> @GowthamGoush , Readme is updated . Take a Look at it again and tell me for any other suggestions.

Hey @Pradhuman-singh5, I had a look at it but could please add some images for the output?

**Comment by Pradhuman-singh5** [comment]
> > @GowthamGoush , Readme is updated . Take a Look at it again and tell me for any other suggestions.
> 
> Hey @Pradhuman-singh5, I had a look at it but could please add some images for the output?

@GowthamGoush , screen shot is added . Check it out.

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged.

**Comment by GowthamGoush** [comment]
Thanks for the patience, @Pradhuman-singh5.

**Pull request merged**
